/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DBconnection;
import static GUI.Pnl_Luong.tbl_luong;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author Minh
 */
public class Frm_Main extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Main
     */
    public Frm_Main() {
        initComponents();
        lblID.setText(Frm_Dangnhap.us);
        Pnl_Hoadon pnl = new Pnl_Hoadon();
        pnlDanhSachHD pnl1 = new pnlDanhSachHD();
        tabMain.add("Hóa đơn", pnl);
        tabMain.add("Danh sách hóa đơn", pnl1);
        btnHoaDon.setBackground(Color.white);
        btnKhachHang.setBackground(Color.getColor("f0f0f0"));
        btnNhanVien.setBackground(Color.getColor("f0f0f0"));
        btnPhieuNhap.setBackground(Color.getColor("f0f0f0"));
        btnSanPham.setBackground(Color.getColor("f0f0f0"));
        btnUser.setBackground(Color.getColor("f0f0f0"));
        btnThongKe.setBackground(Color.getColor("f0f0f0"));
        showtime();
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat s1 = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
                lblDongHo.setText(s.format(d));                
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhung = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlFormtrai = new javax.swing.JPanel();
        lblImageHome = new javax.swing.JLabel();
        pnlKhungXinChao = new javax.swing.JPanel();
        lblXinChao = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        pnlTrangtri = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        pnlDoimk = new javax.swing.JPanel();
        lblDoimk = new javax.swing.JLabel();
        pnlThongtintk = new javax.swing.JPanel();
        lblThongtintk = new javax.swing.JLabel();
        pnlHotro = new javax.swing.JPanel();
        lblHotro = new javax.swing.JLabel();
        pnlDangxuat = new javax.swing.JPanel();
        lblDangxuat = new javax.swing.JLabel();
        pnlFormphai = new javax.swing.JPanel();
        pnlKhungmenu = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        pnlDuocChon = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnPhieuNhap = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlKhung.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlFormtrai.setBackground(new java.awt.Color(50, 22, 112));
        pnlFormtrai.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlFormtraiMouseMoved(evt);
            }
        });

        lblImageHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/trangchu.png"))); // NOI18N

        pnlKhungXinChao.setBackground(new java.awt.Color(95, 132, 206));
        pnlKhungXinChao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblXinChao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblXinChao.setText("Xin chào:");

        lblID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlKhungXinChaoLayout = new javax.swing.GroupLayout(pnlKhungXinChao);
        pnlKhungXinChao.setLayout(pnlKhungXinChaoLayout);
        pnlKhungXinChaoLayout.setHorizontalGroup(
            pnlKhungXinChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungXinChaoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblXinChao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        pnlKhungXinChaoLayout.setVerticalGroup(
            pnlKhungXinChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungXinChaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKhungXinChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblXinChao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTrangtri.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTrangtriLayout = new javax.swing.GroupLayout(pnlTrangtri);
        pnlTrangtri.setLayout(pnlTrangtriLayout);
        pnlTrangtriLayout.setHorizontalGroup(
            pnlTrangtriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTrangtriLayout.setVerticalGroup(
            pnlTrangtriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 255, 255));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Alarm.png"))); // NOI18N

        pnlDoimk.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoimk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDoimk.setBackground(new java.awt.Color(255, 255, 255));
        lblDoimk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDoimk.setText("             Đổi mật khẩu");
        lblDoimk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDoimk.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblDoimkMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDoimkMouseMoved(evt);
            }
        });
        lblDoimk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoimkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoimkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoimkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlDoimkLayout = new javax.swing.GroupLayout(pnlDoimk);
        pnlDoimk.setLayout(pnlDoimkLayout);
        pnlDoimkLayout.setHorizontalGroup(
            pnlDoimkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoimk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDoimkLayout.setVerticalGroup(
            pnlDoimkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoimk, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pnlThongtintk.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongtintk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlThongtintk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongtintkMouseEntered(evt);
            }
        });

        lblThongtintk.setBackground(new java.awt.Color(255, 255, 255));
        lblThongtintk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblThongtintk.setText("       Thông tin tài khoản");
        lblThongtintk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblThongtintk.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblThongtintkMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThongtintkMouseMoved(evt);
            }
        });
        lblThongtintk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongtintkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongtintkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongtintkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlThongtintkLayout = new javax.swing.GroupLayout(pnlThongtintk);
        pnlThongtintk.setLayout(pnlThongtintkLayout);
        pnlThongtintkLayout.setHorizontalGroup(
            pnlThongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongtintk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlThongtintkLayout.setVerticalGroup(
            pnlThongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongtintk, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pnlHotro.setBackground(new java.awt.Color(255, 255, 255));
        pnlHotro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHotro.setBackground(new java.awt.Color(255, 255, 255));
        lblHotro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHotro.setText("       Hỗ trợ");
        lblHotro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblHotro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblHotroMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblHotroMouseMoved(evt);
            }
        });
        lblHotro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHotroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHotroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHotroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlHotroLayout = new javax.swing.GroupLayout(pnlHotro);
        pnlHotro.setLayout(pnlHotroLayout);
        pnlHotroLayout.setHorizontalGroup(
            pnlHotroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotroLayout.createSequentialGroup()
                .addComponent(lblHotro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlHotroLayout.setVerticalGroup(
            pnlHotroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHotro, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        pnlDangxuat.setBackground(new java.awt.Color(255, 255, 255));
        pnlDangxuat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDangxuat.setBackground(new java.awt.Color(255, 255, 255));
        lblDangxuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDangxuat.setText("   Đăng xuất");
        lblDangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDangxuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblDangxuatMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDangxuatMouseMoved(evt);
            }
        });
        lblDangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangxuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangxuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlDangxuatLayout = new javax.swing.GroupLayout(pnlDangxuat);
        pnlDangxuat.setLayout(pnlDangxuatLayout);
        pnlDangxuatLayout.setHorizontalGroup(
            pnlDangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDangxuatLayout.createSequentialGroup()
                .addComponent(lblDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDangxuatLayout.setVerticalGroup(
            pnlDangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlFormtraiLayout = new javax.swing.GroupLayout(pnlFormtrai);
        pnlFormtrai.setLayout(pnlFormtraiLayout);
        pnlFormtraiLayout.setHorizontalGroup(
            pnlFormtraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTrangtri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFormtraiLayout.createSequentialGroup()
                .addGroup(pnlFormtraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormtraiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlFormtraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlKhungXinChao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlDoimk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlThongtintk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlFormtraiLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblImageHome)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlFormtraiLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFormtraiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlHotro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlFormtraiLayout.setVerticalGroup(
            pnlFormtraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormtraiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImageHome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(pnlKhungXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlThongtintk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283)
                .addGroup(pnlFormtraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHotro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTrangtri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDongHo)
                .addContainerGap())
        );

        pnlFormphai.setBackground(new java.awt.Color(255, 255, 255));

        pnlKhungmenu.setBackground(new java.awt.Color(204, 204, 255));

        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hoadon.png"))); // NOI18N
        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        pnlDuocChon.setBackground(new java.awt.Color(204, 204, 255));

        tabMain.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pnlDuocChonLayout = new javax.swing.GroupLayout(pnlDuocChon);
        pnlDuocChon.setLayout(pnlDuocChonLayout);
        pnlDuocChonLayout.setHorizontalGroup(
            pnlDuocChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDuocChonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        pnlDuocChonLayout.setVerticalGroup(
            pnlDuocChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDuocChonLayout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/khachhang_1.png"))); // NOI18N
        btnKhachHang.setText("KHÁCH HÀNG");
        btnKhachHang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Businessman-people-icon_1.png"))); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/phieunhap.png"))); // NOI18N
        btnPhieuNhap.setText("PHIẾU NHẬP");
        btnPhieuNhap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPhieuNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhieuNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhapActionPerformed(evt);
            }
        });

        btnSanPham.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sanpham.png"))); // NOI18N
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user.png"))); // NOI18N
        btnUser.setText("USER");
        btnUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/thongke.png"))); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKhungmenuLayout = new javax.swing.GroupLayout(pnlKhungmenu);
        pnlKhungmenu.setLayout(pnlKhungmenuLayout);
        pnlKhungmenuLayout.setHorizontalGroup(
            pnlKhungmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungmenuLayout.createSequentialGroup()
                .addGroup(pnlKhungmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDuocChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlKhungmenuLayout.createSequentialGroup()
                        .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlKhungmenuLayout.setVerticalGroup(
            pnlKhungmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungmenuLayout.createSequentialGroup()
                .addGroup(pnlKhungmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDuocChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnlFormphaiLayout = new javax.swing.GroupLayout(pnlFormphai);
        pnlFormphai.setLayout(pnlFormphaiLayout);
        pnlFormphaiLayout.setHorizontalGroup(
            pnlFormphaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormphaiLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlKhungmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 989, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pnlFormphaiLayout.setVerticalGroup(
            pnlFormphaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormphaiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlKhungmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlFormtrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlFormphai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormphai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlFormtrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlKhungLayout = new javax.swing.GroupLayout(pnlKhung);
        pnlKhung.setLayout(pnlKhungLayout);
        pnlKhungLayout.setHorizontalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlKhungLayout.setVerticalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        Pnl_Hoadon pnl = new Pnl_Hoadon();
        pnlDanhSachHD pnl1 = new pnlDanhSachHD();
        tabMain.removeAll();
        tabMain.add("Hóa đơn",pnl);
        tabMain.add("Danh sách hóa đơn",pnl1);
        btnHoaDon.setBackground(Color.white);
        btnKhachHang.setBackground(Color.getColor("f0f0f0"));
        btnNhanVien.setBackground(Color.getColor("f0f0f0"));
        btnPhieuNhap.setBackground(Color.getColor("f0f0f0"));
        btnSanPham.setBackground(Color.getColor("f0f0f0"));
        btnUser.setBackground(Color.getColor("f0f0f0"));
        btnThongKe.setBackground(Color.getColor("f0f0f0"));
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
         Pnl_Khachhang pnl2 = new Pnl_Khachhang();
        tabMain.removeAll();
        tabMain.add("Quản lý khách hàng", pnl2);
        BLL.BLL_Khachhang.DoDuLieu(Pnl_Khachhang.Tbl_Khachhang);
        btnKhachHang.setBackground(Color.white);
        btnHoaDon.setBackground(Color.getColor("f0f0f0"));
        btnNhanVien.setBackground(Color.getColor("f0f0f0"));
        btnPhieuNhap.setBackground(Color.getColor("f0f0f0"));
        btnSanPham.setBackground(Color.getColor("f0f0f0"));
        btnUser.setBackground(Color.getColor("f0f0f0"));
        btnThongKe.setBackground(Color.getColor("f0f0f0"));
        
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        Pnl_Qlnhanvien pnl = new Pnl_Qlnhanvien();
        Pnl_Luong pnl1 = new Pnl_Luong();
        tabMain.removeAll();
        tabMain.add("Quản lý nhân viên", pnl);
        tabMain.add("Quản lý lương", pnl1);
        btnNhanVien.setBackground(Color.white);
        btnKhachHang.setBackground(Color.getColor("f0f0f0"));
        btnHoaDon.setBackground(Color.getColor("f0f0f0"));
        btnPhieuNhap.setBackground(Color.getColor("f0f0f0"));
        btnSanPham.setBackground(Color.getColor("f0f0f0"));
        btnUser.setBackground(Color.getColor("f0f0f0"));
        btnThongKe.setBackground(Color.getColor("f0f0f0"));
   
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
        Pnl_Phieunhap pnl = new Pnl_Phieunhap();
        tabMain.removeAll();
        tabMain.add("Phiếu nhập",pnl);  
        btnPhieuNhap.setBackground(Color.white);
        btnKhachHang.setBackground(Color.getColor("f0f0f0"));
        btnNhanVien.setBackground(Color.getColor("f0f0f0"));
        btnHoaDon.setBackground(Color.getColor("f0f0f0"));
        btnSanPham.setBackground(Color.getColor("f0f0f0"));
        btnUser.setBackground(Color.getColor("f0f0f0"));
        btnThongKe.setBackground(Color.getColor("f0f0f0"));
    }//GEN-LAST:event_btnPhieuNhapActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        Pnl_Sanpham pnl1 = new Pnl_Sanpham();
        Pnl_Nhacungcap pnl2 = new Pnl_Nhacungcap();
        Pnl_Loaisanpham pnl3 = new Pnl_Loaisanpham();
        tabMain.removeAll();

        tabMain.add("Quản lý sản phẩm", pnl1);
        tabMain.add("Quản lý nhà cung cấp", pnl2);
        tabMain.add("Quản lý loại sản phẩm", pnl3);
        btnSanPham.setBackground(Color.white);
        btnKhachHang.setBackground(Color.getColor("f0f0f0"));
        btnNhanVien.setBackground(Color.getColor("f0f0f0"));
        btnPhieuNhap.setBackground(Color.getColor("f0f0f0"));
        btnHoaDon.setBackground(Color.getColor("f0f0f0"));
        btnUser.setBackground(Color.getColor("f0f0f0"));
        btnThongKe.setBackground(Color.getColor("f0f0f0"));


    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        Pnl_User pnl = new Pnl_User();
        tabMain.removeAll();
        tabMain.add("Quản lí User", pnl);
        BLL.BLL_User.DoDuLieu(Pnl_User.tblUser);
        btnUser.setBackground(Color.white);
        btnKhachHang.setBackground(Color.getColor("f0f0f0"));
        btnNhanVien.setBackground(Color.getColor("f0f0f0"));
        btnPhieuNhap.setBackground(Color.getColor("f0f0f0"));
        btnSanPham.setBackground(Color.getColor("f0f0f0"));
        btnHoaDon.setBackground(Color.getColor("f0f0f0"));
        btnThongKe.setBackground(Color.getColor("f0f0f0"));
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        pnlThongKe pnl = new pnlThongKe();
        tabMain.removeAll();
        tabMain.add("Thống kê", pnl);
        btnThongKe.setBackground(Color.white);
        btnKhachHang.setBackground(Color.getColor("f0f0f0"));
        btnNhanVien.setBackground(Color.getColor("f0f0f0"));
        btnPhieuNhap.setBackground(Color.getColor("f0f0f0"));
        btnSanPham.setBackground(Color.getColor("f0f0f0"));
        btnUser.setBackground(Color.getColor("f0f0f0"));
        btnHoaDon.setBackground(Color.getColor("f0f0f0"));
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        if (Frm_Dangnhap.quyen.equals("2")) {
            btnNhanVien.setEnabled(false);
            btnUser.setEnabled(false);
            btnThongKe.setEnabled(false);
            btnSanPham.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void lblDoimkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseClicked
               Jdl_Doimatkhau jdl = new Jdl_Doimatkhau(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_lblDoimkMouseClicked

    private void lblDoimkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseMoved

    }//GEN-LAST:event_lblDoimkMouseMoved

    private void pnlFormtraiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFormtraiMouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_pnlFormtraiMouseMoved

    private void lblDoimkMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseDragged
      
    }//GEN-LAST:event_lblDoimkMouseDragged

    private void lblDoimkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseEntered
            
        pnlDoimk.setBackground(new Color(41,22,50));
        lblDoimk.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblDoimkMouseEntered

    private void lblDoimkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseExited
    
        pnlDoimk.setBackground(Color.white);
        lblDoimk.setForeground(Color.black);
    }//GEN-LAST:event_lblDoimkMouseExited

    private void lblThongtintkMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongtintkMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThongtintkMouseDragged

    private void lblThongtintkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongtintkMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThongtintkMouseMoved

    private void lblThongtintkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongtintkMouseClicked
         Jdl_Thongtintk jdl = new Jdl_Thongtintk(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_lblThongtintkMouseClicked

    private void lblThongtintkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongtintkMouseEntered
          pnlThongtintk.setBackground(new Color(41,22,50));
        lblThongtintk.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblThongtintkMouseEntered

    private void lblThongtintkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongtintkMouseExited
      
        pnlThongtintk.setBackground(Color.white);
        lblThongtintk.setForeground(Color.black);
    }//GEN-LAST:event_lblThongtintkMouseExited

    private void pnlThongtintkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongtintkMouseEntered
     
    }//GEN-LAST:event_pnlThongtintkMouseEntered

    private void lblHotroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHotroMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHotroMouseDragged

    private void lblHotroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHotroMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHotroMouseMoved

    private void lblHotroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHotroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHotroMouseClicked

    private void lblHotroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHotroMouseEntered
               pnlHotro.setBackground(new Color(41,22,50));
        lblHotro.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblHotroMouseEntered

    private void lblHotroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHotroMouseExited
        pnlHotro.setBackground(Color.white);
        lblHotro.setForeground(Color.black);
    }//GEN-LAST:event_lblHotroMouseExited

    private void lblDangxuatMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangxuatMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDangxuatMouseDragged

    private void lblDangxuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangxuatMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDangxuatMouseMoved

    private void lblDangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangxuatMouseClicked
               this.dispose();
        Frm_Dangnhap frm = new Frm_Dangnhap();
        frm.setVisible(true);
    }//GEN-LAST:event_lblDangxuatMouseClicked

    private void lblDangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangxuatMouseEntered
         pnlDangxuat.setBackground(new Color(41,22,50));
        lblDangxuat.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblDangxuatMouseEntered

    private void lblDangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangxuatMouseExited
         pnlDangxuat.setBackground(Color.white);
        lblDangxuat.setForeground(Color.black);
    }//GEN-LAST:event_lblDangxuatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDangxuat;
    private javax.swing.JLabel lblDoimk;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHotro;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImageHome;
    private javax.swing.JLabel lblThongtintk;
    private javax.swing.JLabel lblXinChao;
    private javax.swing.JPanel pnlDangxuat;
    private javax.swing.JPanel pnlDoimk;
    private javax.swing.JPanel pnlDuocChon;
    private javax.swing.JPanel pnlFormphai;
    private javax.swing.JPanel pnlFormtrai;
    private javax.swing.JPanel pnlHotro;
    private javax.swing.JPanel pnlKhung;
    private javax.swing.JPanel pnlKhungXinChao;
    private javax.swing.JPanel pnlKhungmenu;
    private javax.swing.JPanel pnlThongtintk;
    private javax.swing.JPanel pnlTrangtri;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
