/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_DoiMK;
import java.awt.Color;

/**
 *
 * @author Minh
 */
public class Jdl_Doimatkhau extends javax.swing.JDialog {

    /**
     * Creates new form Jdl_Thongtintaikhoan
     */
    public Jdl_Doimatkhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtTenTK.setText(Frm_Dangnhap.us);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhungchinh = new javax.swing.JPanel();
        pnlKhung = new javax.swing.JPanel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblMKMoi = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        pnlTrangtri = new javax.swing.JPanel();
        lblNhapLaiMK = new javax.swing.JLabel();
        txtMKMoi = new javax.swing.JPasswordField();
        txtNhapLaiMK = new javax.swing.JPasswordField();
        lblMKCu = new javax.swing.JLabel();
        txtMKCu = new javax.swing.JPasswordField();
        pnlDoimk = new javax.swing.JPanel();
        lblDoimk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlKhungchinh.setBackground(new java.awt.Color(255, 255, 255));

        pnlKhung.setBackground(new java.awt.Color(95, 132, 206));
        pnlKhung.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTaiKhoan.setText("Tên tài khoản");

        lblMKMoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMKMoi.setText("Mật khẩu mới");

        txtTenTK.setEditable(false);
        txtTenTK.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTenTK.setForeground(new java.awt.Color(255, 0, 0));
        txtTenTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTKActionPerformed(evt);
            }
        });

        pnlTrangtri.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTrangtriLayout = new javax.swing.GroupLayout(pnlTrangtri);
        pnlTrangtri.setLayout(pnlTrangtriLayout);
        pnlTrangtriLayout.setHorizontalGroup(
            pnlTrangtriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTrangtriLayout.setVerticalGroup(
            pnlTrangtriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        lblNhapLaiMK.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNhapLaiMK.setText("Nhập lại MK");

        txtMKMoi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        txtNhapLaiMK.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lblMKCu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMKCu.setText("Mật khẩu cũ");

        txtMKCu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        pnlDoimk.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoimk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDoimk.setBackground(new java.awt.Color(50, 22, 112));
        lblDoimk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDoimk.setText("   Đổi mật khẩu");
        lblDoimk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDoimk.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblDoimkMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDoimkMouseMoved(evt);
            }
        });
        lblDoimk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoimkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoimkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoimkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlDoimkLayout = new javax.swing.GroupLayout(pnlDoimk);
        pnlDoimk.setLayout(pnlDoimkLayout);
        pnlDoimkLayout.setHorizontalGroup(
            pnlDoimkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoimk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        pnlDoimkLayout.setVerticalGroup(
            pnlDoimkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoimkLayout.createSequentialGroup()
                .addComponent(lblDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKhungLayout = new javax.swing.GroupLayout(pnlKhung);
        pnlKhung.setLayout(pnlKhungLayout);
        pnlKhungLayout.setHorizontalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTrangtri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlKhungLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlKhungLayout.createSequentialGroup()
                                .addComponent(lblMKMoi)
                                .addGap(18, 18, 18)
                                .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlKhungLayout.createSequentialGroup()
                                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNhapLaiMK))
                                    .addComponent(lblMKCu))
                                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlKhungLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMKCu, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(txtTenTK)))
                                    .addGroup(pnlKhungLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlKhungLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(pnlDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        pnlKhungLayout.setVerticalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTrangtri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaiKhoan)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMKCu)
                    .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMKMoi)
                    .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapLaiMK)
                    .addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlDoimk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKhungchinhLayout = new javax.swing.GroupLayout(pnlKhungchinh);
        pnlKhungchinh.setLayout(pnlKhungchinhLayout);
        pnlKhungchinhLayout.setHorizontalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhungchinhLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlKhungchinhLayout.setVerticalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhungchinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhungchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTKActionPerformed

    private void lblDoimkMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseDragged

    }//GEN-LAST:event_lblDoimkMouseDragged

    private void lblDoimkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseMoved

    }//GEN-LAST:event_lblDoimkMouseMoved

    private void lblDoimkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseClicked
  DTO.DTO_DoiMK doiMK = new DTO_DoiMK();
        doiMK.setTenTK(txtTenTK.getText());
        doiMK.setMKCu(String.valueOf(txtMKCu.getPassword()));
        doiMK.setMKMoi(String.valueOf(txtMKMoi.getPassword()));
        doiMK.setNhapLaiMK(String.valueOf(txtNhapLaiMK.getPassword()));
        boolean kq = BLL.BLL_DoiMK.KiemTra(doiMK);
        if (kq) {
            ThongBao.ThongBao("Đổi mật khẩu thành công", "Thông báo");
            DAO.DAO_DangNhap.DoiMK(doiMK);
            this.dispose();
        }  
    }//GEN-LAST:event_lblDoimkMouseClicked

    private void lblDoimkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseEntered

        pnlDoimk.setBackground(new Color(95,132,206));
        lblDoimk.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblDoimkMouseEntered

    private void lblDoimkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoimkMouseExited

        pnlDoimk.setBackground(Color.white);
        lblDoimk.setForeground(Color.black);
    }//GEN-LAST:event_lblDoimkMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jdl_Doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jdl_Doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jdl_Doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jdl_Doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jdl_Doimatkhau dialog = new Jdl_Doimatkhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDoimk;
    private javax.swing.JLabel lblMKCu;
    private javax.swing.JLabel lblMKMoi;
    private javax.swing.JLabel lblNhapLaiMK;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JPanel pnlDoimk;
    private javax.swing.JPanel pnlKhung;
    private javax.swing.JPanel pnlKhungchinh;
    private javax.swing.JPanel pnlTrangtri;
    private javax.swing.JPasswordField txtMKCu;
    private javax.swing.JPasswordField txtMKMoi;
    private javax.swing.JPasswordField txtNhapLaiMK;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
