/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DTO.DTO_Khachhang;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class jdlThemNhanhNCC extends javax.swing.JDialog {

    /**
     * Creates new form jdlThemNhanhKH
     */
    public jdlThemNhanhNCC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhungchinh = new javax.swing.JPanel();
        lblMaNCC = new javax.swing.JLabel();
        lblThemNcc = new javax.swing.JLabel();
        txtMancc = new javax.swing.JTextField();
        lblTenNCC = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        lblSdt = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDiachi = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlKhungchinh.setBackground(new java.awt.Color(204, 204, 255));

        lblMaNCC.setText("Mã nhà cung cấp:");

        lblThemNcc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThemNcc.setText("THÊM NHÀ CUNG CẤP");

        txtMancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManccActionPerformed(evt);
            }
        });

        lblTenNCC.setText("Tên nhà cung cấp:");

        lblSdt.setText("Số điện thoại:");

        lblEmail.setText("Email:");

        lblDiachi.setText("Địa chỉ:");

        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKhungchinhLayout = new javax.swing.GroupLayout(pnlKhungchinh);
        pnlKhungchinh.setLayout(pnlKhungchinhLayout);
        pnlKhungchinhLayout.setHorizontalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                        .addComponent(lblSdt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                        .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenNCC)
                            .addComponent(lblMaNCC)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(txtMancc)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                        .addComponent(lblDiachi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhungchinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThemNcc)
                .addGap(81, 81, 81))
        );
        pnlKhungchinhLayout.setVerticalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThemNcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNCC)
                    .addComponent(txtMancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNCC)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSdt))
                .addGap(18, 18, 18)
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiachi))
                .addGap(32, 32, 32)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhungchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhungchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        DTO.DTO_NCC NCC = new DTO.DTO_NCC();
        NCC.setMaNCC(txtMancc.getText());
        NCC.setTenNCC(txtTenNCC.getText());
        NCC.setEmail(txtEmail.getText());
        NCC.setSdt(txtSdt.getText());
        NCC.setDiachi(txtDiachi.getText());
        NCC.setGhichu("");
        if (KiemTra(NCC)) {
            ThongBao.ThongBao("Thêm thành công", "Thông báo");
            DAO.DAO_NCC.ThemNCC(NCC);
            this.dispose();
            BLL.BLL_Phieunhap.DoDuLieucbbNCC(Pnl_Phieunhap.cbbNhacungcap);
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void txtManccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManccActionPerformed
    private static boolean KiemTra(DTO.DTO_NCC NCC) {
    if (NCC.getMaNCC().trim().length() < 1 || NCC.getMaNCC().trim().length() > 10) {
            ThongBao.ThongBao("Mã nhà cung cấp không hợp lệ", "Thông báo");
            return false;
        }
//        System.out.println(NCC.getMaNCC());
        ResultSet rs = DAO.DAO_NCC.GetMaNCC();
        try {
            while (rs.next()) {

                if (rs.getString("MaNCC").equals(NCC.getMaNCC())) {
                    ThongBao.ThongBao("Mã nhà cung cấp đã được sử dụng", "Thông báo");
                    return false;
                }
            }
        } catch (Exception e) {
            System.out.println("haha");
        }
        if (NCC.getTenNCC().trim().length() < 1) {
            ThongBao.ThongBao("Tên nhà cung cấp không được để trống", "Thông báo");
            return false;
        }
        if (NCC.getDiachi().trim().length() < 1) {
            ThongBao.ThongBao("Địa chỉ không được để trống", "Thông báo");
            return false;
        }

        String KTSDT = "\\d{10}";
        if (!NCC.getSdt().matches(KTSDT)) {
            ThongBao.ThongBao("SDT không hợp lệ", "Thông báo");
            return false;
        }

        String KTEmail = "\\w+@\\w+(\\.\\w+){1,2}";
        if (!NCC.getEmail().matches(KTEmail)) {
            ThongBao.ThongBao("Email không hợp lệ", "Thông báo");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlThemNhanhNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlThemNhanhNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlThemNhanhNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlThemNhanhNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlThemNhanhNCC dialog = new jdlThemNhanhNCC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMaNCC;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JLabel lblTenNCC;
    private javax.swing.JLabel lblThemNcc;
    private javax.swing.JPanel pnlKhungchinh;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMancc;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
