/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DAO.DBconnection;
import DTO.DTO_CTHD;
import DTO.DTO_CTPN;
import DTO.DTO_HoaDon;
import DTO.DTO_PhieuNhap;
import static GUI.Jdl_Thongtintk.MaNV;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Minh
 */
public class Pnl_Phieunhap extends javax.swing.JPanel {
//public static DBconnection conn;

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Phieunhap() {
        initComponents();
        LoaDataCBBLoaiSP();
        ResultSet rs = DAO.DAO_Phieunhap.GetAllSP();
        BLL.BLL_Phieunhap.DoDuLieuTbSP(tbl_SP, rs);
        BLL.BLL_Phieunhap.DoDuLieucbbNCC(cbbNhacungcap);
        BLL.BLL_Phieunhap.DoDuLieucbbSP(cbbTensanpham);
        LayTenNV();
//        LayMaHD();
            txtSophieu.setText(SoHoaDon());
        showtime();
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();

                SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
                txtNgaytao.setText(s.format(d));
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPhieunhap = new javax.swing.JPanel();
        pnlDanhsachSP = new javax.swing.JPanel();
        lblTensp = new javax.swing.JLabel();
        txtGianhap = new javax.swing.JTextField();
        spnSoLuong = new javax.swing.JSpinner();
        lblGianhap = new javax.swing.JLabel();
        lblSoluong = new javax.swing.JLabel();
        txtTimSP = new javax.swing.JTextField();
        pnlDanhsachsp = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_SP = new javax.swing.JTable();
        cbbLoaiSP = new javax.swing.JComboBox<>();
        txtSearchSP = new javax.swing.JTextField();
        cbbTensanpham = new javax.swing.JComboBox<>();
        lblTimSP = new javax.swing.JLabel();
        pnlThongtinNCC = new javax.swing.JPanel();
        lblTimNCC = new javax.swing.JLabel();
        txtSearchNCC = new javax.swing.JTextField();
        lblNhacungcap = new javax.swing.JLabel();
        cbbNhacungcap = new javax.swing.JComboBox<>();
        lblDiachi = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        lblSdt = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        btnThemKH = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_CTPN = new javax.swing.JTable();
        btnChon = new javax.swing.JToggleButton();
        btnLamMoi = new javax.swing.JToggleButton();
        pnlThongtinchung = new javax.swing.JPanel();
        pnlNgaytao = new javax.swing.JLabel();
        pnlSophieu = new javax.swing.JLabel();
        pnlNhanvien = new javax.swing.JLabel();
        txtNgaytao = new javax.swing.JTextField();
        txtSophieu = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        lblGhichu = new javax.swing.JLabel();
        txtGhichu = new javax.swing.JTextField();
        pnlTongcong = new javax.swing.JPanel();
        lblTongcong = new javax.swing.JLabel();
        txtTongcong = new javax.swing.JTextField();
        btnXuatphieu = new javax.swing.JToggleButton();

        pnlDanhsachSP.setBackground(new java.awt.Color(204, 204, 255));
        pnlDanhsachSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));

        lblTensp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTensp.setText("Tên sản phẩm");

        txtGianhap.setEnabled(false);

        spnSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblGianhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGianhap.setText("Giá nhập");

        lblSoluong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSoluong.setText("Số lượng");

        txtTimSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimSPKeyReleased(evt);
            }
        });

        pnlDanhsachsp.setBackground(new java.awt.Color(204, 204, 255));
        pnlDanhsachsp.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));

        jScrollPane4.setBackground(new java.awt.Color(204, 204, 255));

        tbl_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ", "Tên sản phẩm", "Tồn kho", "Giá nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_SP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_SP);

        cbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        cbbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiSPActionPerformed(evt);
            }
        });

        txtSearchSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchSPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlDanhsachspLayout = new javax.swing.GroupLayout(pnlDanhsachsp);
        pnlDanhsachsp.setLayout(pnlDanhsachspLayout);
        pnlDanhsachspLayout.setHorizontalGroup(
            pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnlDanhsachspLayout.createSequentialGroup()
                .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDanhsachspLayout.setVerticalGroup(
            pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhsachspLayout.createSequentialGroup()
                .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        cbbTensanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTensanphamActionPerformed(evt);
            }
        });

        lblTimSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimSP.setText("Tìm sản phẩm");

        javax.swing.GroupLayout pnlDanhsachSPLayout = new javax.swing.GroupLayout(pnlDanhsachSP);
        pnlDanhsachSP.setLayout(pnlDanhsachSPLayout);
        pnlDanhsachSPLayout.setHorizontalGroup(
            pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhsachSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGianhap)
                    .addComponent(lblSoluong)
                    .addComponent(lblTensp)
                    .addComponent(lblTimSP))
                .addGroup(pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDanhsachSPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDanhsachSPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbTensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhsachSPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlDanhsachsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDanhsachSPLayout.setVerticalGroup(
            pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhsachSPLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimSP))
                .addGap(9, 9, 9)
                .addGroup(pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTensp)
                    .addComponent(cbbTensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoluong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDanhsachSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGianhap))
                .addGap(18, 18, 18)
                .addComponent(pnlDanhsachsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlThongtinNCC.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinNCC.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà cung cấp"));

        lblTimNCC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimNCC.setText("Tìm nhà cung cấp");

        txtSearchNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNCCKeyReleased(evt);
            }
        });

        lblNhacungcap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNhacungcap.setText("Nhà cung cấp");

        cbbNhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhacungcapActionPerformed(evt);
            }
        });

        lblDiachi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiachi.setText("Địa chỉ");

        txtDiachi.setEnabled(false);

        lblSdt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSdt.setText("Điện thoại");

        txtSdt.setEnabled(false);

        btnThemKH.setText("+");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongtinNCCLayout = new javax.swing.GroupLayout(pnlThongtinNCC);
        pnlThongtinNCC.setLayout(pnlThongtinNCCLayout);
        pnlThongtinNCCLayout.setHorizontalGroup(
            pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimNCC)
                    .addComponent(lblNhacungcap)
                    .addComponent(lblDiachi)
                    .addComponent(lblSdt))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongtinNCCLayout.createSequentialGroup()
                        .addComponent(cbbNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        pnlThongtinNCCLayout.setVerticalGroup(
            pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinNCCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimNCC)
                    .addComponent(txtSearchNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhacungcap)
                    .addComponent(cbbNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiachi)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSdt)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlTable.setBackground(new java.awt.Color(204, 204, 255));
        pnlTable.setBorder(javax.swing.BorderFactory.createTitledBorder("  "));

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        tbl_CTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane3.setViewportView(tbl_CTPN);

        btnChon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add to basket.png"))); // NOI18N
        btnChon.setText("THÊM ");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableLayout.createSequentialGroup()
                        .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout.createSequentialGroup()
                .addGroup(pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        pnlThongtinchung.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinchung.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chung"));

        pnlNgaytao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pnlNgaytao.setText("Ngày tạo");

        pnlSophieu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pnlSophieu.setText("Số phiếu");

        pnlNhanvien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pnlNhanvien.setText("Nhân viên");

        txtNgaytao.setEnabled(false);

        txtSophieu.setEnabled(false);

        txtTenNV.setEnabled(false);
        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        lblGhichu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGhichu.setText("Ghi chú");

        javax.swing.GroupLayout pnlThongtinchungLayout = new javax.swing.GroupLayout(pnlThongtinchung);
        pnlThongtinchung.setLayout(pnlThongtinchungLayout);
        pnlThongtinchungLayout.setHorizontalGroup(
            pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinchungLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGhichu)
                    .addComponent(pnlSophieu)
                    .addComponent(pnlNgaytao)
                    .addComponent(pnlNhanvien))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSophieu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhichu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlThongtinchungLayout.setVerticalGroup(
            pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinchungLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlNgaytao)
                    .addComponent(txtNgaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlSophieu)
                    .addComponent(txtSophieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlNhanvien)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinchungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhichu)
                    .addComponent(txtGhichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlTongcong.setBackground(new java.awt.Color(204, 204, 255));
        pnlTongcong.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTongcong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTongcong.setText("TỔNG CỘNG:");

        btnXuatphieu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuatphieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Payment.png"))); // NOI18N
        btnXuatphieu.setText("XUẤT PHIẾU");
        btnXuatphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatphieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTongcongLayout = new javax.swing.GroupLayout(pnlTongcong);
        pnlTongcong.setLayout(pnlTongcongLayout);
        pnlTongcongLayout.setHorizontalGroup(
            pnlTongcongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongcongLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblTongcong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXuatphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        pnlTongcongLayout.setVerticalGroup(
            pnlTongcongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongcongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnXuatphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblTongcong))
        );

        javax.swing.GroupLayout pnlPhieunhapLayout = new javax.swing.GroupLayout(pnlPhieunhap);
        pnlPhieunhap.setLayout(pnlPhieunhapLayout);
        pnlPhieunhapLayout.setHorizontalGroup(
            pnlPhieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhieunhapLayout.createSequentialGroup()
                .addComponent(pnlDanhsachSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlPhieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhieunhapLayout.createSequentialGroup()
                        .addComponent(pnlThongtinNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlThongtinchung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTongcong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlPhieunhapLayout.setVerticalGroup(
            pnlPhieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDanhsachSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPhieunhapLayout.createSequentialGroup()
                .addGroup(pnlPhieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThongtinNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlThongtinchung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPhieunhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPhieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public static int SoLuong;
    public static int soluongchon;
    public static String MaSP;
    public static int tonkho;
    public static int SL;

//    private void LayMaHD() {
//        ResultSet rs = DAO.DAO_HoaDon.GetMaHDMax();
//        try {
//            while (rs.next()) {
//                txtMaHD.setText(String.valueOf(rs.getInt("MaHD") + 1));
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Pnl_Hoadon.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    private void LayTenNV() {
        ResultSet rs = DAO.DAO_User.GetUserTheoMaUS(Frm_Dangnhap.us);
        try {
            while (rs.next()) {
                MaNV = rs.getString("MaNV");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Phieunhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs1 = DAO.DAO_NhanVien.GetNhanVien_TheoMa(MaNV);
        try {
            while (rs1.next()) {
                txtTenNV.setText(rs1.getString("TenNV"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Phieunhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private double TinhTien() {
        double tongTien = 0;
        for (int i = 0; i < tbl_CTPN.getRowCount(); i++) {
            tongTien += BLL_ChuyenDoi.ChuyenSangSo(tbl_CTPN.getValueAt(i, 5).toString());
        }

        return tongTien;
    }
    private void txtSearchNCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNCCKeyReleased
        try {
            if (txtSearchNCC.getText().length() == 0) {
                BLL.BLL_Phieunhap.DoDuLieucbbNCC(cbbNhacungcap);
            }
            BLL.BLL_Phieunhap.DoDuLieuVaoCBBNCC(cbbNhacungcap, txtSearchNCC.getText());
            My_CBB mb = (My_CBB) cbbNhacungcap.getSelectedItem();
            String MaNCC = mb.value.toString();
            ResultSet rs = DAO.DAO_Phieunhap.GetNCCTheoMa(MaNCC);
            try {

                while (rs.next()) {
                    txtDiachi.setText(rs.getString("DiaChi"));
                    txtSdt.setText(rs.getString("SDT"));
                }
            } catch (SQLException ex) {
                ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSearchNCCKeyReleased

    private void cbbNhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhacungcapActionPerformed
        try {
            My_CBB mb = (My_CBB) cbbNhacungcap.getSelectedItem();
            String MaNCC = mb.value.toString();
            ResultSet rs = DAO.DAO_Phieunhap.GetNCCTheoMa(MaNCC);
            try {
                while (rs.next()) {
                    txtDiachi.setText(rs.getString("DiaChi"));
                    txtSdt.setText(rs.getString("SDT"));
                }
            } catch (SQLException ex) {
                ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbbNhacungcapActionPerformed

    private void ThemSPtbCTPN() {
        soluongchon = Integer.parseInt(spnSoLuong.getModel().getValue().toString());
        try {
            DefaultTableModel tbModel = (DefaultTableModel) tbl_CTPN.getModel();
        Object obj[] = new Object[6];
        int vitri = tbl_SP.getSelectedRow();
        int cacdong = tbl_CTPN.getRowCount();
        
        
          if (tbl_CTPN.getRowCount() == 0) {
            obj[0] = tbModel.getRowCount() + 1;
            My_CBB mb = (My_CBB)cbbTensanpham.getSelectedItem();
            obj[1] = mb.value.toString();
            obj[2] = cbbTensanpham.getSelectedItem();
            obj[3] = spnSoLuong.getValue();
            obj[4] = txtGianhap.getText();
            obj[5] = BLL_ChuyenDoi.DinhDangSo(BLL_ChuyenDoi.ChuyenSangSo(txtGianhap.getText()) * soluongchon);
            tbModel.addRow(obj);
            

          } else if (tbl_CTPN.getRowCount() > 0) {
               
            for (int i = 0; i < cacdong; i++) {
               
                My_CBB mb1 = (My_CBB) cbbTensanpham.getSelectedItem();
                String MaSP = mb1.value.toString();
                String LuuMaSP = tbl_CTPN.getValueAt(i, 1).toString();
                int soluonghientai = Integer.parseInt(tbl_CTPN.getValueAt(i, 3).toString());
                double Tui = BLL_ChuyenDoi.ChuyenSangSo(tbl_CTPN.getValueAt(i, 4).toString());
                
                if (MaSP.equals(LuuMaSP)) {
                 
                    System.out.println(soluonghientai + soluongchon);
                    tbl_CTPN.setValueAt(soluonghientai + soluongchon, i, 3);
                    tbl_CTPN.setValueAt(BLL_ChuyenDoi.DinhDangSo(Tui * (soluonghientai + soluongchon)), i, 5);
//                    tbl_SP.setValueAt(tonkho-soluongchon, tbl_SP.getSelectedRow(), 2);
                    return;
                }
//                tbl_SP.setValueAt(tonkho - soluongchon, tbl_SP.getSelectedRow(), 2);
            }
//
             obj[0] = tbModel.getRowCount() + 1;
            My_CBB mb = (My_CBB)cbbTensanpham.getSelectedItem();
            obj[1] = mb.value.toString();
            obj[2] = cbbTensanpham.getSelectedItem();
            obj[3] = spnSoLuong.getValue();
            obj[4] = txtGianhap.getText();
            obj[5] = BLL_ChuyenDoi.DinhDangSo(BLL_ChuyenDoi.ChuyenSangSo(txtGianhap.getText()) * soluongchon);
            tbModel.addRow(obj);

        }
        } catch (Exception e) {
        }

    }

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed

        

        
//        System.out.println(soluongchon);
//        tbl_SP.setValueAt(tonkho - soluongchon, tbl_SP.getSelectedRow(), 2);
        ThemSPtbCTPN();
        txtTongcong.setText(BLL_ChuyenDoi.DinhDangSo(TinhTien()));

    }//GEN-LAST:event_btnChonActionPerformed
    private void LamMoi() {
        cbbLoaiSP.setSelectedIndex(0);
        cbbTensanpham.setSelectedIndex(0);
        txtSearchSP.setText("");
        txtTimSP.setText("");
        spnSoLuong.setValue(1);

        txtSearchNCC.setText("");
        cbbNhacungcap.setSelectedIndex(0);
        DefaultTableModel tbModel = (DefaultTableModel) tbl_CTPN.getModel();
        tbModel.setRowCount(0);
        txtTongcong.setText("");

//        LayMaHD();
        txtSophieu.setText(SoHoaDon());
    }

        private String SoHoaDon() {
        String soHoaDon = "";
        try {

            DateFormat dateFormat = new SimpleDateFormat("yyMMdd");

            Date d = new Date();

            soHoaDon = dateFormat.format(d);
//            System.out.println("soHoaDon: " + soHoaDon);
            ResultSet rs = DAO.DAO_Phieunhap.CountSoHoaDon(soHoaDon);
            int rowCount = 0;
            if (rs.next()) {
                rowCount = rs.getInt(1);
            }
            boolean dup = false;
            do {
                if (rowCount > 98) {
                    soHoaDon = soHoaDon + (rowCount + 1);
                } else if (rowCount > 8) {
                    soHoaDon = soHoaDon + "0" + (rowCount + 1);
                } else {
                    soHoaDon = soHoaDon + "00" + (rowCount + 1);
                }
//                System.out.println("soHoaDon: " + soHoaDon);
                ResultSet rs2 = DAO.DAO_Phieunhap.GetBySoHoaDon(soHoaDon);
                if (rs2.next()) {
                    dup = true;
                    rowCount++;
                    soHoaDon = dateFormat.format(d);
                } else {
                    dup = false;
                }
            } while (dup);

        } catch (SQLException ex) {
            System.out.println("Lỗi số hóa đơn");
        }

        return soHoaDon;
    }

    public void XuatPhieuNhap(int MaPN) {
        try {
            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src/GUI/rptXuatPN.jrxml");

            map.put("MaPN", MaPN);
//            System.out.println(map.put("MaHD", idhd));
            JasperPrint p = JasperFillManager.fillReport(report, map, DBconnection.conn);
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "test.pdf");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        LamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXuatphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatphieuActionPerformed
        DTO.DTO_PhieuNhap PN = new DTO_PhieuNhap();
        PN.setMaPN(txtSophieu.getText());
        My_CBB mb = (My_CBB) cbbNhacungcap.getSelectedItem();
        String MaNCC = mb.value.toString();
        PN.setMaNCC(MaNCC);
        PN.setMoTa(txtGhichu.getText());
        PN.setNgayLap(txtNgaytao.getText());
        PN.setTenTK(Frm_Dangnhap.us);
        double tongTien = BLL_ChuyenDoi.ChuyenSangSo(txtTongcong.getText());
        PN.setTongTien(tongTien);
        DAO.DAO_Phieunhap.ThemPN(PN);

        DTO.DTO_CTPN CTPN = new DTO_CTPN();
        for (int i = 0; i < tbl_CTPN.getRowCount(); i++) {
            ResultSet rsMaPN = DAO.DAO_Phieunhap.GetMaPNMax();
            try {
                while (rsMaPN.next()) {
                    CTPN.setMaPN(rsMaPN.getInt("MaPN"));
                }
            } catch (SQLException ex) {

            }
            CTPN.setMaSP(tbl_CTPN.getValueAt(i, 1).toString());
            CTPN.setMoTa(txtGhichu.getText());
            CTPN.setSoLuong(Integer.parseInt(tbl_CTPN.getValueAt(i, 3).toString()));
            CTPN.setThanhTien(BLL_ChuyenDoi.ChuyenSangSo(tbl_CTPN.getValueAt(i, 5).toString()));
            DAO.DAO_CTPN.ThemCTPN(CTPN);
            ResultSet rs = DAO.DAO_Phieunhap.getSLSP(tbl_CTPN.getValueAt(i, 1).toString());
            try {
                while (rs.next()) {
                    int SLKho = rs.getInt("TonKho");
                    DAO.DAO_Phieunhap.UpdateSLSP(SLKho, Integer.parseInt(tbl_CTPN.getValueAt(i, 3).toString()),
                            tbl_CTPN.getValueAt(i, 1).toString());
                }
            } catch (SQLException ex) {

            }

        }
        ResultSet rs = DAO.DAO_Phieunhap.GetAllSP();
        BLL.BLL_Phieunhap.DoDuLieuTbSP(tbl_SP, rs);
        XuatPhieuNhap(CTPN.getMaPN());
        LamMoi();
    }//GEN-LAST:event_btnXuatphieuActionPerformed

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void tbl_SPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SPMouseClicked

    }//GEN-LAST:event_tbl_SPMouseClicked

    private void cbbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiSPActionPerformed
        if (cbbLoaiSP.getSelectedItem().equals("Tất cả")) {
            BLL.BLL_Phieunhap.DoDuLieuTbSP(tbl_SP, DAO.DAO_Phieunhap.SearchTuKhoa(txtSearchSP.getText()));
        } else {
            My_CBB mb = (My_CBB) cbbLoaiSP.getSelectedItem();
            String maLoaiSP = mb.value.toString();
            BLL.BLL_Phieunhap.DoDuLieuTbSP(tbl_SP, DAO.DAO_Phieunhap.SearchTheoMaLoaiSP(maLoaiSP));
        }
     
    }//GEN-LAST:event_cbbLoaiSPActionPerformed

    private void txtSearchSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchSPKeyReleased
        if (cbbLoaiSP.getSelectedItem().equals("Tất cả")) {
            BLL.BLL_Phieunhap.DoDuLieuTbSP(tbl_SP, DAO.DAO_Phieunhap.SearchTuKhoa(txtSearchSP.getText()));
        } else {
            My_CBB mb = (My_CBB) cbbLoaiSP.getSelectedItem();
            String maLoaiSP = mb.value.toString();
            BLL.BLL_Phieunhap.DoDuLieuTbSP(tbl_SP, DAO.DAO_Phieunhap.SearchSP(txtSearchSP.getText(), maLoaiSP));
        }
    }//GEN-LAST:event_txtSearchSPKeyReleased

    private void txtTimSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimSPKeyReleased
        try {
            if (txtTimSP.getText().length() == 0) {
                BLL.BLL_Phieunhap.DoDuLieucbbSP(cbbTensanpham);
            }
            
            BLL.BLL_Phieunhap.DoDuLieucbbSP(cbbTensanpham, txtTimSP.getText());
            
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_txtTimSPKeyReleased

    private void cbbTensanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTensanphamActionPerformed
              try {
            My_CBB mb = (My_CBB) cbbTensanpham.getSelectedItem();
            String MaSP = mb.value.toString();
            ResultSet rs = DAO.DAO_Phieunhap.GetSPTheoMa(MaSP);
            try {
                while (rs.next()) {
                    txtGianhap.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("GiaNhap")));
                   
                }
            } catch (SQLException ex) {
                ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_cbbTensanphamActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        jdlThemNhanhNCC jdl = new jdlThemNhanhNCC(run.jdl, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void LoaDataCBBLoaiSP() {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbLoaiSP.getModel();
        ResultSet rs = DAO.DAO_HoaDon.GetAllLoaiSP();
        try {
            while (rs.next()) {
                Object tenLoai = rs.getString("TenLoaiSP");
                Object maLoai = rs.getString("MaLoaiSP");
                My_CBB mb = new My_CBB(maLoai, tenLoai);
                cbbModel.addElement(mb);
            }
        } catch (SQLException ex) {
            ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnChon;
    private javax.swing.JToggleButton btnLamMoi;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JToggleButton btnXuatphieu;
    private javax.swing.JComboBox<String> cbbLoaiSP;
    public static javax.swing.JComboBox<String> cbbNhacungcap;
    private javax.swing.JComboBox<String> cbbTensanpham;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblGianhap;
    private javax.swing.JLabel lblNhacungcap;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JLabel lblSoluong;
    private javax.swing.JLabel lblTensp;
    private javax.swing.JLabel lblTimNCC;
    private javax.swing.JLabel lblTimSP;
    private javax.swing.JLabel lblTongcong;
    private javax.swing.JPanel pnlDanhsachSP;
    private javax.swing.JPanel pnlDanhsachsp;
    private javax.swing.JLabel pnlNgaytao;
    private javax.swing.JLabel pnlNhanvien;
    private javax.swing.JPanel pnlPhieunhap;
    private javax.swing.JLabel pnlSophieu;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlThongtinNCC;
    private javax.swing.JPanel pnlThongtinchung;
    private javax.swing.JPanel pnlTongcong;
    private javax.swing.JSpinner spnSoLuong;
    public static javax.swing.JTable tbl_CTPN;
    public static javax.swing.JTable tbl_SP;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtGhichu;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtNgaytao;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSearchNCC;
    private javax.swing.JTextField txtSearchSP;
    private javax.swing.JTextField txtSophieu;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimSP;
    private javax.swing.JTextField txtTongcong;
    // End of variables declaration//GEN-END:variables
}
