/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DTO.DTO_Luong;
import static GUI.Pnl_Qlnhanvien.tblNhanVien;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Minh
 */
public class Pnl_Luong extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Luong() {
        initComponents();
        LoaDataCBBNhanVien();
        GetMaLuong();
        NgayHienTai();
        BLL.BLL_Luong.DoDuLieu(tbl_luong);
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();

                SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
                txtNgayLam.setText(s.format(d));
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhung = new javax.swing.JPanel();
        pnlThongtinluong = new javax.swing.JPanel();
        pnlNhanvien = new javax.swing.JPanel();
        lblTimNV = new javax.swing.JLabel();
        txtTimNhanVien = new javax.swing.JTextField();
        lblNhanvien = new javax.swing.JLabel();
        cbbNhanVien = new javax.swing.JComboBox<>();
        lblNgaylam = new javax.swing.JLabel();
        txtNgayLam = new javax.swing.JTextField();
        lblGhichu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        lblTimkiem = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        pnlngaylam = new javax.swing.JPanel();
        lblLuonggio = new javax.swing.JLabel();
        lblSongaylam = new javax.swing.JLabel();
        spnSoGioLam = new javax.swing.JSpinner();
        txtLuong1Gio = new javax.swing.JTextField();
        txtMaLuong = new javax.swing.JTextField();
        lblMaluong = new javax.swing.JLabel();
        lblLuonglamthem = new javax.swing.JLabel();
        txtLuongLamThem = new javax.swing.JTextField();
        lblLuongngay = new javax.swing.JLabel();
        txtLuong1Ngay = new javax.swing.JTextField();
        pnlTacvu = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_luong = new javax.swing.JTable();
        pnlTimNV = new javax.swing.JPanel();
        lblTungay = new javax.swing.JLabel();
        jdcNgayBD = new com.toedter.calendar.JDateChooser();
        lblDenngay = new javax.swing.JLabel();
        jdcNgayKT = new com.toedter.calendar.JDateChooser();
        btnXemLuong = new javax.swing.JButton();
        lblLuongthang = new javax.swing.JLabel();
        txtLuong1Thang = new javax.swing.JTextField();
        lblTenNV = new javax.swing.JLabel();
        cbbNV = new javax.swing.JComboBox<>();
        lbltimNV1 = new javax.swing.JLabel();
        txtTimNV = new javax.swing.JTextField();

        pnlKhung.setBackground(new java.awt.Color(204, 204, 255));

        pnlThongtinluong.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinluong.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin lương"));

        pnlNhanvien.setBackground(new java.awt.Color(204, 204, 255));
        pnlNhanvien.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhân viên"));

        lblTimNV.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTimNV.setText("Tìm nhân viên");

        txtTimNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimNhanVienKeyReleased(evt);
            }
        });

        lblNhanvien.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblNhanvien.setText("Nhân viên");

        cbbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhanVienActionPerformed(evt);
            }
        });

        lblNgaylam.setBackground(new java.awt.Color(204, 204, 255));
        lblNgaylam.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblNgaylam.setText("Ngày làm");

        lblGhichu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGhichu.setText("Ghi chú");

        lblTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimkiem.setText("TÌM KIẾM");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanvienLayout = new javax.swing.GroupLayout(pnlNhanvien);
        pnlNhanvien.setLayout(pnlNhanvienLayout);
        pnlNhanvienLayout.setHorizontalGroup(
            pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNhanvienLayout.createSequentialGroup()
                        .addComponent(lblNhanvien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNhanvienLayout.createSequentialGroup()
                        .addComponent(lblTimNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(txtTimNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNhanvienLayout.createSequentialGroup()
                        .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgaylam)
                            .addComponent(lblGhichu)
                            .addComponent(lblTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtNgayLam)))))
                .addGap(20, 20, 20))
        );
        pnlNhanvienLayout.setVerticalGroup(
            pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanvienLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhanvien)
                    .addComponent(cbbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgaylam)
                    .addComponent(txtNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGhichu))
                .addGap(18, 18, 18)
                .addGroup(pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimkiem)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlngaylam.setBackground(new java.awt.Color(204, 204, 255));
        pnlngaylam.setBorder(javax.swing.BorderFactory.createTitledBorder("Ngày làm"));

        lblLuonggio.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblLuonggio.setText("Lương/giờ");

        lblSongaylam.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblSongaylam.setText("Số giờ làm/ngày");

        spnSoGioLam.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        txtLuong1Gio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLuong1GioKeyReleased(evt);
            }
        });

        txtMaLuong.setFocusable(false);

        lblMaluong.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblMaluong.setText("Mã lương");

        lblLuonglamthem.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblLuonglamthem.setText("Lương làm thêm:");

        txtLuongLamThem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLuongLamThemKeyReleased(evt);
            }
        });

        lblLuongngay.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblLuongngay.setText("Lương/ ngày       ");

        txtLuong1Ngay.setEnabled(false);
        txtLuong1Ngay.setFocusable(false);
        txtLuong1Ngay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLuong1NgayKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlngaylamLayout = new javax.swing.GroupLayout(pnlngaylam);
        pnlngaylam.setLayout(pnlngaylamLayout);
        pnlngaylamLayout.setHorizontalGroup(
            pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlngaylamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSongaylam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaluong)
                    .addComponent(lblLuonggio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuonglamthem)
                    .addComponent(lblLuongngay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLuong1Ngay)
                    .addComponent(txtLuongLamThem)
                    .addComponent(txtLuong1Gio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlngaylamLayout.createSequentialGroup()
                        .addComponent(spnSoGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addComponent(txtMaLuong))
                .addContainerGap())
        );
        pnlngaylamLayout.setVerticalGroup(
            pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlngaylamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSongaylam)
                    .addComponent(spnSoGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaluong)
                    .addComponent(txtMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuonggio)
                    .addComponent(txtLuong1Gio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuonglamthem)
                    .addComponent(txtLuongLamThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlngaylamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLuongngay)
                    .addComponent(txtLuong1Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTacvu.setBackground(new java.awt.Color(204, 204, 255));
        pnlTacvu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Edit.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnMoi.setText(" MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTacvuLayout = new javax.swing.GroupLayout(pnlTacvu);
        pnlTacvu.setLayout(pnlTacvuLayout);
        pnlTacvuLayout.setHorizontalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlTacvuLayout.setVerticalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlThongtinluongLayout = new javax.swing.GroupLayout(pnlThongtinluong);
        pnlThongtinluong.setLayout(pnlThongtinluongLayout);
        pnlThongtinluongLayout.setHorizontalGroup(
            pnlThongtinluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinluongLayout.createSequentialGroup()
                .addGroup(pnlThongtinluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongtinluongLayout.createSequentialGroup()
                        .addComponent(pnlNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlngaylam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTacvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlThongtinluongLayout.setVerticalGroup(
            pnlThongtinluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinluongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlngaylam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTacvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTable.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        tbl_luong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã lương", "Nhân viên", "Lương 1 giờ", "Số giờ làm/ngày", "Ngày làm", "Lương làm thêm", "Tổng lương 1 ngày", "Mô tả"
            }
        ));
        tbl_luong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_luongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_luong);
        if (tbl_luong.getColumnModel().getColumnCount() > 0) {
            tbl_luong.getColumnModel().getColumn(0).setMinWidth(30);
            tbl_luong.getColumnModel().getColumn(0).setMaxWidth(40);
            tbl_luong.getColumnModel().getColumn(1).setMinWidth(50);
            tbl_luong.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTimNV.setBackground(new java.awt.Color(204, 204, 255));
        pnlTimNV.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ"));
        pnlTimNV.setAutoscrolls(true);

        lblTungay.setText("Từ ngày:");

        jdcNgayBD.setDateFormatString("dd-MM-yyyy");

        lblDenngay.setText("Đến ngày:");

        jdcNgayKT.setDateFormatString("dd-MM-yyyy");

        btnXemLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXemLuong.setText("Xem lương");
        btnXemLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLuongActionPerformed(evt);
            }
        });

        lblLuongthang.setText("Tổng lương/ tháng:");

        lblTenNV.setText("Nhân viên:");

        lbltimNV1.setText("Tìm nhân viên");

        txtTimNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimNVKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTimNVLayout = new javax.swing.GroupLayout(pnlTimNV);
        pnlTimNV.setLayout(pnlTimNVLayout);
        pnlTimNVLayout.setHorizontalGroup(
            pnlTimNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTimNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdcNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtLuong1Thang)
                    .addComponent(cbbNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTimNV)
                    .addGroup(pnlTimNVLayout.createSequentialGroup()
                        .addGroup(pnlTimNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTungay)
                            .addComponent(lblDenngay)
                            .addComponent(lblLuongthang)
                            .addComponent(lblTenNV)
                            .addComponent(lbltimNV1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTimNVLayout.setVerticalGroup(
            pnlTimNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimNVLayout.createSequentialGroup()
                .addComponent(lbltimNV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTungay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDenngay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnXemLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblLuongthang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLuong1Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout pnlKhungLayout = new javax.swing.GroupLayout(pnlKhung);
        pnlKhung.setLayout(pnlKhungLayout);
        pnlKhungLayout.setHorizontalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLayout.createSequentialGroup()
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlKhungLayout.createSequentialGroup()
                        .addComponent(pnlThongtinluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlKhungLayout.setVerticalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThongtinluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public static int sogiolam;
    public static double luong1gio;
    public static double luonglamthem;
    public static double luong1ngay;
    private void txtTimNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimNhanVienKeyReleased
        BLL.BLL_Luong.DoDuLieuVaoCBBNhanVien(cbbNhanVien, txtTimNhanVien.getText());
    }//GEN-LAST:event_txtTimNhanVienKeyReleased
    private void NgayHienTai() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String time = sdf.format(date.getTime());
        txtNgayLam.setText(time);
    }
    private void txtLuong1NgayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuong1NgayKeyReleased
        String chuoi = txtLuong1Ngay.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtLuong1Ngay.setText(sotien);
//        String chuoi = txtLuong.getText();
//        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
//        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
//        txtLuong.setText(sotien);
//        try {
//            Date date1 = null;
//            Date date2 = null;
//            date1 = dcsNgayBatDau.getDate();
//            date2 = dcsNgayKetThuc.getDate();
//            long getDiff = date2.getTime() - date1.getTime();
//            long getDaysDiff = getDiff / (24 * 60 * 60 * 1000);
//            songaytrongthang = Integer.parseInt(String.valueOf(getDaysDiff)) + 1;
//            songaynghi = Integer.parseInt(spnSoNgayNghi.getValue().toString());
//            songaylam = songaytrongthang - songaynghi;
////            System.out.println(songaylam);
//            luong = BLL_ChuyenDoi.ChuyenSangSo(txtLuong.getText());
//            if (songaylam > 0) {
//                txtTongLuong.setText(BLL_ChuyenDoi.DinhDangSo(songaylam * luong));
//            }
//        } catch (Exception e) {
//            txtTongLuong.setText("0");
//        }
    }//GEN-LAST:event_txtLuong1NgayKeyReleased

    private void tbl_luongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_luongMouseClicked
        int vitri = tbl_luong.getSelectedRow();
        txtMaLuong.setText(tbl_luong.getValueAt(vitri, 1).toString());
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbNhanVien.getModel();
        for (int i = 0; i < cbbNhanVien.getItemCount(); i++) {
            My_CBB mb = (My_CBB) cbbModel.getElementAt(i);
            String tenNV = mb.text.toString();
            if (tenNV.equals((tbl_luong.getValueAt(vitri, 2)))) {
                cbbNhanVien.setSelectedIndex(i);
            }
        }
        txtLuong1Gio.setText(tbl_luong.getValueAt(vitri, 3).toString());
        spnSoGioLam.setValue(tbl_luong.getValueAt(vitri, 4));
        txtNgayLam.setText(tbl_luong.getValueAt(vitri, 5).toString());
        txtLuongLamThem.setText(tbl_luong.getValueAt(vitri, 6).toString());
        txtLuong1Ngay.setText(tbl_luong.getValueAt(vitri, 7).toString());
        txtGhiChu.setText(tbl_luong.getValueAt(vitri, 8).toString());
    }//GEN-LAST:event_tbl_luongMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        BLL.BLL_Luong.DoDuLieu(tbl_luong, BLL_ChuyenDoi.getDate(txtSearch.getText()).toString());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        LamMoi();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tbl_luong.getSelectedRowCount()!= 1) {
             ThongBao.ThongBao("Bạn chưa chọn dòng để xóa", "Thông báo");
            return;
        } else {
               int kq = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có chắc chắn muốn xóa không",
                "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_luong.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                int MaLuong = Integer.parseInt(tbl_luong.getValueAt(cacdong[i], 1).toString());
                DAO.DAO_Luong.Xoa(MaLuong);
            }
        }
        BLL.BLL_Luong.DoDuLieu(tbl_luong);
        LamMoi();
        }
     
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DTO.DTO_Luong luong = new DTO_Luong();
        int sodongduocchon = tbl_luong.getSelectedRowCount();
        if (sodongduocchon != 1) {
            ThongBao.ThongBao("Bạn cần chọn 1 dòng để sửa", "Thông báo");
            return;
        }
        int vitri = tbl_luong.getSelectedRow();
        My_CBB mb = (My_CBB) cbbNhanVien.getSelectedItem();
        luong.setMaNV(mb.value.toString());
        luong.setMoTa(txtGhiChu.getText());
        luong.setLuong1Gio(BLL_ChuyenDoi.ChuyenSangSo(txtLuong1Gio.getText()));
        luong.setNgayLam(txtNgayLam.getText());
        luong.setSoGioLam(Integer.parseInt(spnSoGioLam.getModel().getValue().toString()));
        luong.setTongLuong1Ngay(BLL_ChuyenDoi.ChuyenSangSo(txtLuong1Ngay.getText()));
        luong.setMaLuong(Integer.parseInt(tbl_luong.getValueAt(vitri, 1).toString()));
        luong.setLuongLamThem(BLL_ChuyenDoi.ChuyenSangSo(txtLuongLamThem.getText()));

//
        boolean kq = BLL.BLL_Luong.KiemTra(luong);
        if (kq) {
            DAO.DAO_Luong.Sua(luong);
            BLL.BLL_Luong.DoDuLieu(tbl_luong);
            LamMoi();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        DTO.DTO_Luong luong = new DTO_Luong();
        luong.setMaLuong(Integer.parseInt(txtMaLuong.getText()));
        My_CBB mb = (My_CBB) cbbNhanVien.getSelectedItem();
        luong.setMaNV(mb.value.toString());
        luong.setNgayLam(txtNgayLam.getText());
        luong.setLuong1Gio(BLL_ChuyenDoi.ChuyenSangSo(txtLuong1Gio.getText()));
        luong.setSoGioLam(Integer.parseInt(spnSoGioLam.getModel().getValue().toString()));
        luong.setLuongLamThem(BLL_ChuyenDoi.ChuyenSangSo(txtLuongLamThem.getText()));
        luong.setTongLuong1Ngay(BLL_ChuyenDoi.ChuyenSangSo(txtLuong1Ngay.getText()));
        luong.setMoTa(txtGhiChu.getText());

        if (BLL.BLL_Luong.KiemTra(luong)) {
            DAO.DAO_Luong.ThemLuong(luong);
            BLL.BLL_Luong.DoDuLieu(tbl_luong);
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimNVKeyReleased
        BLL.BLL_Luong.DoDuLieuVaoCBBNhanVien(cbbNV, txtTimNV.getText());
    }//GEN-LAST:event_txtTimNVKeyReleased

    private void txtLuong1GioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuong1GioKeyReleased
        String chuoi = txtLuong1Gio.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtLuong1Gio.setText(sotien);
        sogiolam = Integer.parseInt(spnSoGioLam.getModel().getValue().toString());
        luong1gio = BLL_ChuyenDoi.ChuyenSangSo(txtLuong1Gio.getText());
        txtLuong1Ngay.setText(BLL_ChuyenDoi.DinhDangSo(luong1gio * sogiolam));
    }//GEN-LAST:event_txtLuong1GioKeyReleased

    private void txtLuongLamThemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongLamThemKeyReleased
        String chuoi = txtLuongLamThem.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtLuongLamThem.setText(sotien);
        luonglamthem = BLL_ChuyenDoi.ChuyenSangSo(txtLuongLamThem.getText());
        txtLuong1Ngay.setText(BLL_ChuyenDoi.DinhDangSo(luong1gio * sogiolam + luonglamthem));
    }//GEN-LAST:event_txtLuongLamThemKeyReleased

    private void btnXemLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLuongActionPerformed
        try {
            try {
            Date date1 = null;
            Date date2 = null;
            date1 = jdcNgayBD.getDate();
            date2 = jdcNgayKT.getDate();
            long getDiff = date2.getTime() - date1.getTime();
            long getDaysDiff = getDiff / (24 * 60 * 60 * 1000);
            int songaytrongthang = Integer.parseInt(String.valueOf(getDaysDiff));
            if (songaytrongthang <= 0) {
                txtLuong1Thang.setText("");
            }
        } catch (Exception e) {

        }

        My_CBB mb = (My_CBB) cbbNV.getSelectedItem();
        String MaNV = mb.value.toString();
        ResultSet rs = DAO.DAO_Luong.getTongLuongThang(BLL_ChuyenDoi.GetDate(jdcNgayBD.getDate()), BLL_ChuyenDoi.GetDate(jdcNgayKT.getDate()), MaNV);
        try {
            while (rs.next()) {
                txtLuong1Thang.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("TongLuong")));
                //System.out.println(rs.getDouble("TongLuong"));
            }
        } catch (SQLException ex) {
            ThongBao.ThongBao("Lỗi", "Thông báo");
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXemLuongActionPerformed

    private void cbbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNhanVienActionPerformed
    private void LamMoi() {
        GetMaLuong();
        cbbNhanVien.setSelectedIndex(0);
        cbbNV.setSelectedIndex(0);
        txtGhiChu.setText("");
        jdcNgayBD.setDate(null);
        jdcNgayKT.setDate(null);
        txtLuong1Gio.setText("");
        txtLuong1Ngay.setText("");
        txtLuongLamThem.setText("");
        txtLuong1Thang.setText("");
        txtTimNV.setText("");
        txtTimNhanVien.setText("");
        spnSoGioLam.setValue(1);
        NgayHienTai();
    }

    public static void LoaDataCBBNhanVien() {
        cbbNV.removeAllItems();
        cbbNhanVien.removeAllItems();
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbNhanVien.getModel();
        DefaultComboBoxModel cbbModel1 = (DefaultComboBoxModel) cbbNV.getModel();
        ResultSet rs = DAO.DAO_NhanVien.GetALL();
        try {
            while (rs.next()) {
                Object ten = rs.getString("TenNV");
                Object ma = rs.getString("MaNV");
                My_CBB mb = new My_CBB(ma, ten);
                cbbModel.addElement(mb);
                cbbModel1.addElement(mb);
            }
        } catch (SQLException ex) {
            ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
        }
    }

    private void GetMaLuong() {
        ResultSet rs = DAO.DAO_Luong.GetMaLuong();
        try {
            while (rs.next()) {
                txtMaLuong.setText(String.valueOf(rs.getInt("MaLuong") + 1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXemLuong;
    private javax.swing.JButton btnXoa;
    public static javax.swing.JComboBox<String> cbbNV;
    public static javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcNgayBD;
    private com.toedter.calendar.JDateChooser jdcNgayKT;
    private javax.swing.JLabel lblDenngay;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblLuonggio;
    private javax.swing.JLabel lblLuonglamthem;
    private javax.swing.JLabel lblLuongngay;
    private javax.swing.JLabel lblLuongthang;
    private javax.swing.JLabel lblMaluong;
    private javax.swing.JLabel lblNgaylam;
    private javax.swing.JLabel lblNhanvien;
    private javax.swing.JLabel lblSongaylam;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTimNV;
    private javax.swing.JLabel lblTimkiem;
    private javax.swing.JLabel lblTungay;
    private javax.swing.JLabel lbltimNV1;
    private javax.swing.JPanel pnlKhung;
    private javax.swing.JPanel pnlNhanvien;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTacvu;
    private javax.swing.JPanel pnlThongtinluong;
    private javax.swing.JPanel pnlTimNV;
    private javax.swing.JPanel pnlngaylam;
    private javax.swing.JSpinner spnSoGioLam;
    public static javax.swing.JTable tbl_luong;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtLuong1Gio;
    private javax.swing.JTextField txtLuong1Ngay;
    private javax.swing.JTextField txtLuong1Thang;
    private javax.swing.JTextField txtLuongLamThem;
    private javax.swing.JTextField txtMaLuong;
    private javax.swing.JTextField txtNgayLam;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTimNV;
    private javax.swing.JTextField txtTimNhanVien;
    // End of variables declaration//GEN-END:variables
}
