/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DAO.DBconnection;
import DTO.DTO_CTHD;
import DTO.DTO_HoaDon;
import static GUI.Jdl_Thongtintk.MaNV;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Minh
 */
public class Pnl_Hoadon extends javax.swing.JPanel {
//public static DBconnection conn;

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Hoadon() {
        initComponents();
        LoaDataCBBLoaiSP();
        ResultSet rs = DAO.DAO_HoaDon.GetAllSP();
        BLL.BLL_HoaDon.DoDuLieuTbSP(tbl_SP, rs);
        BLL.BLL_HoaDon.DuDuLieucbbKH(cbbKhachHang);
        LayTenNV();
//        LayMaHD();
        txtMaHD.setText(SoHoaDon());
        showtime();
        btnThanhToan.setEnabled(false);
        UpdateLoaiKH();
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();

                SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
                txtNgayTao.setText(s.format(d));
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhung = new javax.swing.JPanel();
        pnlDanhsachsp = new javax.swing.JPanel();
        tblSanpham = new javax.swing.JScrollPane();
        tbl_SP = new javax.swing.JTable();
        pnlLoaisp = new javax.swing.JPanel();
        cbbLoaiSP = new javax.swing.JComboBox<>();
        txtSearchSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        lblTensp = new javax.swing.JLabel();
        txtGiaSP = new javax.swing.JTextField();
        spnSoLuong = new javax.swing.JSpinner();
        lblGiaSP = new javax.swing.JLabel();
        lblgiaSP = new javax.swing.JLabel();
        pnlthongtintk = new javax.swing.JPanel();
        lblTimkh = new javax.swing.JLabel();
        txtSearchKH = new javax.swing.JTextField();
        lblKhachhang = new javax.swing.JLabel();
        cbbKhachHang = new javax.swing.JComboBox<>();
        lblDiachi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblDienthoai = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        themKH = new javax.swing.JButton();
        pnlBang = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_CThoadon = new javax.swing.JTable();
        btnChon = new javax.swing.JToggleButton();
        btnLamMoi = new javax.swing.JToggleButton();
        pnlThongtin = new javax.swing.JPanel();
        lblNgaytao = new javax.swing.JLabel();
        lblSoHD = new javax.swing.JLabel();
        lblNhanvien = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        txtMaHD = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        lblGhichu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        pnlThanhtoan = new javax.swing.JPanel();
        lblTongcong = new javax.swing.JLabel();
        txtTongCong = new javax.swing.JTextField();
        lblKhachtra = new javax.swing.JLabel();
        txtKhachTra = new javax.swing.JTextField();
        lblTiendu = new javax.swing.JLabel();
        txtTienDu = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JToggleButton();
        lblGiamgia = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();

        pnlDanhsachsp.setBackground(new java.awt.Color(204, 204, 255));
        pnlDanhsachsp.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));

        tblSanpham.setBackground(new java.awt.Color(204, 204, 255));

        tbl_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ", "Tên sản phẩm", "Tồn kho", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_SP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SPMouseClicked(evt);
            }
        });
        tblSanpham.setViewportView(tbl_SP);
        if (tbl_SP.getColumnModel().getColumnCount() > 0) {
            tbl_SP.getColumnModel().getColumn(0).setMinWidth(40);
            tbl_SP.getColumnModel().getColumn(0).setMaxWidth(50);
            tbl_SP.getColumnModel().getColumn(2).setMinWidth(40);
            tbl_SP.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        pnlLoaisp.setBackground(new java.awt.Color(255, 255, 255));

        cbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        cbbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiSPActionPerformed(evt);
            }
        });

        txtSearchSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchSPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlLoaispLayout = new javax.swing.GroupLayout(pnlLoaisp);
        pnlLoaisp.setLayout(pnlLoaispLayout);
        pnlLoaispLayout.setHorizontalGroup(
            pnlLoaispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaispLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlLoaispLayout.setVerticalGroup(
            pnlLoaispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoaispLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLoaispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchSP))
                .addContainerGap())
        );

        txtTenSP.setEnabled(false);

        lblTensp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTensp.setText("Tên sản phẩm");

        txtGiaSP.setEnabled(false);

        lblGiaSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGiaSP.setText("Giá sản phẩm");

        lblgiaSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblgiaSP.setText("Số lượng");

        javax.swing.GroupLayout pnlDanhsachspLayout = new javax.swing.GroupLayout(pnlDanhsachsp);
        pnlDanhsachsp.setLayout(pnlDanhsachspLayout);
        pnlDanhsachspLayout.setHorizontalGroup(
            pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhsachspLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDanhsachspLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tblSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDanhsachspLayout.createSequentialGroup()
                        .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDanhsachspLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGiaSP)
                                    .addComponent(lblgiaSP)
                                    .addComponent(lblTensp))
                                .addGap(26, 26, 26)
                                .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlDanhsachspLayout.setVerticalGroup(
            pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhsachspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTensp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgiaSP)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDanhsachspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaSP))
                .addContainerGap())
        );

        pnlthongtintk.setBackground(new java.awt.Color(204, 204, 255));
        pnlthongtintk.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        lblTimkh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimkh.setText("Tìm khách hàng");

        txtSearchKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKHKeyReleased(evt);
            }
        });

        lblKhachhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblKhachhang.setText("Khách hàng");

        cbbKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKhachHangActionPerformed(evt);
            }
        });

        lblDiachi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiachi.setText("Địa chỉ");

        txtDiaChi.setEnabled(false);

        lblDienthoai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDienthoai.setText("Điện thoại");

        txtSDT.setEnabled(false);

        themKH.setText("+");
        themKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlthongtintkLayout = new javax.swing.GroupLayout(pnlthongtintk);
        pnlthongtintk.setLayout(pnlthongtintkLayout);
        pnlthongtintkLayout.setHorizontalGroup(
            pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlthongtintkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimkh)
                    .addComponent(lblKhachhang)
                    .addComponent(lblDiachi)
                    .addComponent(lblDienthoai))
                .addGap(18, 18, 18)
                .addGroup(pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchKH, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlthongtintkLayout.createSequentialGroup()
                        .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(themKH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        pnlthongtintkLayout.setVerticalGroup(
            pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlthongtintkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimkh)
                    .addComponent(txtSearchKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhachhang)
                    .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themKH, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiachi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlthongtintkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDienthoai)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlBang.setBackground(new java.awt.Color(204, 204, 255));
        pnlBang.setBorder(javax.swing.BorderFactory.createTitledBorder("  "));

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        tbl_CThoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane3.setViewportView(tbl_CThoadon);

        btnChon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add to basket.png"))); // NOI18N
        btnChon.setText("THÊM ");
        btnChon.setEnabled(false);
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBangLayout = new javax.swing.GroupLayout(pnlBang);
        pnlBang.setLayout(pnlBangLayout);
        pnlBangLayout.setHorizontalGroup(
            pnlBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBangLayout.createSequentialGroup()
                .addGroup(pnlBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBangLayout.createSequentialGroup()
                        .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        pnlBangLayout.setVerticalGroup(
            pnlBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBangLayout.createSequentialGroup()
                .addGroup(pnlBangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlThongtin.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtin.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chung"));

        lblNgaytao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNgaytao.setText("Ngày tạo");

        lblSoHD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSoHD.setText("Số hóa đơn");

        lblNhanvien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNhanvien.setText("Nhân viên");

        txtNgayTao.setEnabled(false);

        txtMaHD.setEnabled(false);

        txtNhanVien.setEnabled(false);

        lblGhichu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGhichu.setText("Ghi chú");

        javax.swing.GroupLayout pnlThongtinLayout = new javax.swing.GroupLayout(pnlThongtin);
        pnlThongtin.setLayout(pnlThongtinLayout);
        pnlThongtinLayout.setHorizontalGroup(
            pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGhichu)
                    .addComponent(lblSoHD)
                    .addComponent(lblNgaytao)
                    .addComponent(lblNhanvien))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlThongtinLayout.setVerticalGroup(
            pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgaytao)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoHD)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhanvien)
                    .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGhichu)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlThanhtoan.setBackground(new java.awt.Color(204, 204, 255));
        pnlThanhtoan.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTongcong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTongcong.setText("Tổng cộng");

        txtTongCong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTongCongKeyReleased(evt);
            }
        });

        lblKhachtra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblKhachtra.setText("Khách trả");

        txtKhachTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKhachTraKeyReleased(evt);
            }
        });

        lblTiendu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTiendu.setText("Tiền dư");

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Payment.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        lblGiamgia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGiamgia.setText("Giảm giá");

        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlThanhtoanLayout = new javax.swing.GroupLayout(pnlThanhtoan);
        pnlThanhtoan.setLayout(pnlThanhtoanLayout);
        pnlThanhtoanLayout.setHorizontalGroup(
            pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanhtoanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlThanhtoanLayout.createSequentialGroup()
                        .addComponent(lblGiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThanhtoanLayout.createSequentialGroup()
                        .addComponent(lblKhachtra)
                        .addGap(18, 18, 18)
                        .addComponent(txtKhachTra)))
                .addGap(24, 24, 24)
                .addGroup(pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTiendu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTongcong, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongCong, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txtTienDu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlThanhtoanLayout.setVerticalGroup(
            pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanhtoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThanhtoanLayout.createSequentialGroup()
                        .addGroup(pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTongcong)
                            .addComponent(txtTongCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiamgia)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiendu)
                            .addComponent(txtKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKhachtra)))
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlKhungLayout = new javax.swing.GroupLayout(pnlKhung);
        pnlKhung.setLayout(pnlKhungLayout);
        pnlKhungLayout.setHorizontalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLayout.createSequentialGroup()
                .addComponent(pnlDanhsachsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKhungLayout.createSequentialGroup()
                        .addComponent(pnlthongtintk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlThongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlThanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        pnlKhungLayout.setVerticalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungLayout.createSequentialGroup()
                .addGroup(pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlthongtintk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlThongtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlDanhsachsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    public static int SoLuong;
    public static int soluongchon;
    public static String MaSP;
    public static int tonkho;
    public static int SL;
    public static double giamgia;

    private void tbl_SPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SPMouseClicked
        try {
            if (tbl_SP.getSelectedRowCount() != 1) {
                btnChon.setEnabled(false);
            } else {
                btnChon.setEnabled(true);
            }
            if (Integer.parseInt(tbl_SP.getValueAt(tbl_SP.getSelectedRow(), 2).toString()) == 0) {
                btnChon.setEnabled(false);
            }
            int vitri = tbl_SP.getSelectedRow();
            SoLuong = (Integer.parseInt(tbl_SP.getValueAt(vitri, 2).toString()));
            spnSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, SoLuong, 1));
            txtTenSP.setText(tbl_SP.getValueAt(vitri, 1).toString());
            txtGiaSP.setText(tbl_SP.getValueAt(vitri, 3).toString());
            MaSP = tbl_SP.getValueAt(vitri, 0).toString();
            tonkho = Integer.parseInt(tbl_SP.getValueAt(vitri, 2).toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_SPMouseClicked
//    private void LayMaHD() {
//        ResultSet rs = DAO.DAO_HoaDon.GetMaHDMax();
//        try {
//            while (rs.next()) {
//                txtMaHD.setText(String.valueOf(rs.getInt("MaHD") + 1));
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Pnl_Hoadon.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    private void LayTenNV() {
        ResultSet rs = DAO.DAO_User.GetUserTheoMaUS(Frm_Dangnhap.us);
        try {
            while (rs.next()) {
                MaNV = rs.getString("MaNV");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs1 = DAO.DAO_NhanVien.GetNhanVien_TheoMa(MaNV);
        try {
            while (rs1.next()) {
                txtNhanVien.setText(rs1.getString("TenNV"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pnl_Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private double TinhTien() {
        double tongTien = 0;
        giamgia = 0;
        for (int i = 0; i < tbl_CThoadon.getRowCount(); i++) {
            My_CBB mb = (My_CBB) cbbKhachHang.getSelectedItem();
            ResultSet rs = DAO.DAO_HoaDon.GetKHTheoMa(mb.value.toString());
            try {
                //tongTien += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString());

                while (rs.next()) {
                    if (rs.getString("LoaiKhachHang").equals("Silver")) {
                        tongTien += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) - (BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) * 5 / 100);
                        giamgia += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) * 5 / 100;
                    } else if (rs.getString("LoaiKhachHang").equals("Gold")) {
                        tongTien += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) - (BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) * 10 / 100);
                        giamgia += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) * 10 / 100;
                    } else if (rs.getString("LoaiKhachHang").equals("Platinum")) {
                        tongTien += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) - (BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) * 15 / 100);
                        giamgia += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()) * 15 / 100;
                    } else {
                        tongTien += BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString());
                        giamgia = 0;
                    }
                }
            } catch (SQLException ex) {

            }
        }

        return tongTien;
    }
    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed

        DTO.DTO_HoaDon HD = new DTO_HoaDon();
        HD.setMaHD(Integer.parseInt(txtMaHD.getText()));
        My_CBB mb = (My_CBB) cbbKhachHang.getSelectedItem();
        String MaKH = mb.value.toString();
        HD.setMaKH(MaKH);
        HD.setMoTa(txtGhiChu.getText());
        HD.setNgayLap(txtNgayTao.getText());
        HD.setTenTK(Frm_Dangnhap.us);
        HD.setGiamGia(BLL_ChuyenDoi.ChuyenSangSo(txtGiamGia.getText()));
        double tongTien = BLL_ChuyenDoi.ChuyenSangSo(txtTongCong.getText());
        HD.setTongTien(tongTien);
        DAO.DAO_HoaDon.ThemHD(HD);

        DTO.DTO_CTHD CTHD = new DTO_CTHD();
        for (int i = 0; i < tbl_CThoadon.getRowCount(); i++) {
            ResultSet rsMaHD = DAO.DAO_HoaDon.GetMaHDMax();
            try {
                while (rsMaHD.next()) {
                    CTHD.setMaHD(rsMaHD.getInt("MaHD"));
                }
            } catch (SQLException ex) {

            }
            CTHD.setMaSP(tbl_CThoadon.getValueAt(i, 1).toString());
            CTHD.setMoTa(txtGhiChu.getText());
            CTHD.setSoLuong(Integer.parseInt(tbl_CThoadon.getValueAt(i, 3).toString()));
            CTHD.setThanhTien(BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()));
            DAO.DAO_CTHD.ThemCTHD(CTHD);
            ResultSet rs = DAO.DAO_HoaDon.getSLSP(tbl_CThoadon.getValueAt(i, 1).toString());
            try {
                while (rs.next()) {
                    int SLKho = rs.getInt("TonKho");
                    DAO.DAO_HoaDon.UpdateSLSP(SLKho, Integer.parseInt(tbl_CThoadon.getValueAt(i, 3).toString()),
                            tbl_CThoadon.getValueAt(i, 1).toString());
                }
            } catch (SQLException ex) {

            }

        }
        UpdateLoaiKH();
        XuatHoaDon(CTHD.getMaHD());
        LamMoi();


    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtSearchSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchSPKeyReleased
        if (cbbLoaiSP.getSelectedItem().equals("Tất cả")) {
            BLL.BLL_HoaDon.DoDuLieuTbSP(tbl_SP, DAO.DAO_HoaDon.SearchTuKhoa(txtSearchSP.getText()));
        } else {
            My_CBB mb = (My_CBB) cbbLoaiSP.getSelectedItem();
            String maLoaiSP = mb.value.toString();
            BLL.BLL_HoaDon.DoDuLieuTbSP(tbl_SP, DAO.DAO_HoaDon.SearchSP(txtSearchSP.getText(), maLoaiSP));
        }
    }//GEN-LAST:event_txtSearchSPKeyReleased

    private void cbbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiSPActionPerformed
        if (cbbLoaiSP.getSelectedItem().equals("Tất cả")) {
            BLL.BLL_HoaDon.DoDuLieuTbSP(tbl_SP, DAO.DAO_HoaDon.SearchTuKhoa(txtSearchSP.getText()));
        } else {
            My_CBB mb = (My_CBB) cbbLoaiSP.getSelectedItem();
            String maLoaiSP = mb.value.toString();
            BLL.BLL_HoaDon.DoDuLieuTbSP(tbl_SP, DAO.DAO_HoaDon.SearchTheoMaLoaiSP(maLoaiSP));
        }
        if (tbl_SP.getSelectedRowCount() != 1) {
            btnChon.setEnabled(false);
        } else {
            btnChon.setEnabled(true);
        }
    }//GEN-LAST:event_cbbLoaiSPActionPerformed

    private void txtSearchKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKHKeyReleased
        try {
            if (txtSearchKH.getText().length() == 0) {
                BLL.BLL_HoaDon.DuDuLieucbbKH(cbbKhachHang);
            }
            BLL.BLL_HoaDon.DoDuLieuVaoCBBKhachHang(cbbKhachHang, txtSearchKH.getText());
            My_CBB mb = (My_CBB) cbbKhachHang.getSelectedItem();
            String MaKH = mb.value.toString();
            ResultSet rs = DAO.DAO_HoaDon.GetKHTheoMa(MaKH);
            try {

                while (rs.next()) {
                    txtDiaChi.setText(rs.getString("DiaChi"));
                    txtSDT.setText(rs.getString("SDT"));
                }
            } catch (SQLException ex) {
                ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSearchKHKeyReleased

    private void cbbKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKhachHangActionPerformed
        try {
            My_CBB mb = (My_CBB) cbbKhachHang.getSelectedItem();
            String MaKH = mb.value.toString();
            ResultSet rs = DAO.DAO_HoaDon.GetKHTheoMa(MaKH);
            try {
                while (rs.next()) {
                    txtDiaChi.setText(rs.getString("DiaChi"));
                    txtSDT.setText(rs.getString("SDT"));
                    txtTongCong.setText(BLL_ChuyenDoi.DinhDangSo(TinhTien()));
                    if (giamgia > 0) {
                        txtGiamGia.setText(BLL_ChuyenDoi.DinhDangSo(giamgia));
                    } else {
                        txtGiamGia.setText("0");
                    }
                }
            } catch (SQLException ex) {
                ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_cbbKhachHangActionPerformed

    private void ThemSPtbCTHD() {
        DefaultTableModel tbModel = (DefaultTableModel) tbl_CThoadon.getModel();
        Object obj[] = new Object[6];
        int vitri = tbl_SP.getSelectedRow();
        int cacdong = tbl_CThoadon.getRowCount();

        if (Integer.parseInt(tbl_SP.getValueAt(vitri, 2).toString()) == 0) {
            System.out.println(Integer.parseInt(tbl_SP.getValueAt(vitri, 2).toString()));
            btnChon.setEnabled(false);
            spnSoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 0));
        }
        if (tbl_CThoadon.getRowCount() == 0) {
            obj[0] = tbModel.getRowCount() + 1;
            obj[1] = tbl_SP.getValueAt(vitri, 0).toString();
            obj[2] = tbl_SP.getValueAt(vitri, 1).toString();
            obj[3] = soluongchon;
            obj[4] = tbl_SP.getValueAt(vitri, 3).toString();
            obj[5] = BLL_ChuyenDoi.DinhDangSo(BLL_ChuyenDoi.ChuyenSangSo(tbl_SP.getValueAt(vitri, 3).toString()) * soluongchon);
            tbModel.addRow(obj);

        } else if (tbl_CThoadon.getRowCount() > 0) {
            for (int i = 0; i < cacdong; i++) {
                String masp = tbl_CThoadon.getValueAt(i, 1).toString();
                int soluonghientai = Integer.parseInt(tbl_CThoadon.getValueAt(i, 3).toString());

                if (MaSP.equals(masp)) {
                    tbl_CThoadon.setValueAt(soluonghientai + soluongchon, i, 3);
                    tbl_CThoadon.setValueAt(BLL_ChuyenDoi.DinhDangSo(BLL_ChuyenDoi.ChuyenSangSo(tbl_SP.getValueAt(vitri, 3).toString()) * (soluonghientai + soluongchon)), i, 5);
                    BLL_ChuyenDoi.DinhDangSo(BLL_ChuyenDoi.ChuyenSangSo(tbl_SP.getValueAt(vitri, 3).toString()) * (soluonghientai + soluongchon));

                    return;
                }

            }

            obj[0] = tbModel.getRowCount() + 1;
            obj[1] = tbl_SP.getValueAt(vitri, 0).toString();
            obj[2] = tbl_SP.getValueAt(vitri, 1).toString();
            obj[3] = soluongchon;
            obj[4] = tbl_SP.getValueAt(vitri, 3).toString();
            obj[5] = BLL_ChuyenDoi.DinhDangSo(BLL_ChuyenDoi.ChuyenSangSo(tbl_SP.getValueAt(vitri, 3).toString()) * soluongchon);
            tbModel.addRow(obj);

        }

    }

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        btnThanhToan.setEnabled(true);
        soluongchon = Integer.parseInt(spnSoLuong.getModel().getValue().toString());

        btnChon.setEnabled(false);
//        System.out.println(soluongchon);
        tbl_SP.setValueAt(tonkho - soluongchon, tbl_SP.getSelectedRow(), 2);
        ThemSPtbCTHD();
        txtTongCong.setText(BLL_ChuyenDoi.DinhDangSo(TinhTien()));
        if (giamgia > 0) {
            txtGiamGia.setText(BLL_ChuyenDoi.DinhDangSo(giamgia));
        } else {
            txtGiamGia.setText("0");
        }


    }//GEN-LAST:event_btnChonActionPerformed

    private void txtKhachTraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhachTraKeyReleased
        String chuoi = txtKhachTra.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtKhachTra.setText(sotien);
        double tongTien = BLL_ChuyenDoi.ChuyenSangSo(txtTongCong.getText());
        double khachtra = BLL_ChuyenDoi.ChuyenSangSo(txtKhachTra.getText());
        txtTienDu.setText(BLL_ChuyenDoi.DinhDangSo(khachtra - tongTien));
    }//GEN-LAST:event_txtKhachTraKeyReleased
    private void LamMoi() {
        cbbLoaiSP.setSelectedIndex(0);
        txtSearchSP.setText("");
        txtTenSP.setText("");
        spnSoLuong.setValue(0);
        txtGiaSP.setText("");
        txtSearchKH.setText("");
        cbbKhachHang.setSelectedIndex(0);
        DefaultTableModel tbModel = (DefaultTableModel) tbl_CThoadon.getModel();
        tbModel.setRowCount(0);
        txtTongCong.setText("0");
        txtKhachTra.setText("");
        txtTienDu.setText("");
//        LayMaHD();
        txtMaHD.setText(SoHoaDon());
        btnThanhToan.setEnabled(false);
        txtGiamGia.setText("0");
    }

    private void UpdateLoaiKH() {
        My_CBB mb = (My_CBB) cbbKhachHang.getSelectedItem();
        ResultSet rs = DAO.DAO_HoaDon.getTongTientheoMaKH(mb.value.toString());
        try {
            while (rs.next()) {
                if (rs.getDouble("TongTien") > 10000000 && rs.getDouble("TongTien") < 50000000) {
                    DAO.DAO_HoaDon.UpdateLoaiKH(mb.value.toString(), "Silver");
                } else if (rs.getDouble("TongTien") >= 50000000 && rs.getDouble("TongTien") < 100000000) {
                    DAO.DAO_HoaDon.UpdateLoaiKH(mb.value.toString(), "Gold");
                } else if (rs.getDouble("TongTien") >= 100000000) {
                    DAO.DAO_HoaDon.UpdateLoaiKH(mb.value.toString(), "Platinum");
                }
            }
        } catch (SQLException ex) {
            ThongBao.ThongBao("Lỗi", "Thông báo");
        }
    }

    private String SoHoaDon() {
        String soHoaDon = "";
        try {

            DateFormat dateFormat = new SimpleDateFormat("yyMMdd");

            Date d = new Date();

            soHoaDon = dateFormat.format(d);
//            System.out.println("soHoaDon: " + soHoaDon);
            ResultSet rs = DAO.DAO_HoaDon.CountSoHoaDon(soHoaDon);
            int rowCount = 0;
            if (rs.next()) {
                rowCount = rs.getInt(1);
            }
            boolean dup = false;
            do {
                if (rowCount > 98) {
                    soHoaDon = soHoaDon + (rowCount + 1);
                } else if (rowCount > 8) {
                    soHoaDon = soHoaDon + "0" + (rowCount + 1);
                } else {
                    soHoaDon = soHoaDon + "00" + (rowCount + 1);
                }
//                System.out.println("soHoaDon: " + soHoaDon);
                ResultSet rs2 = DAO.DAO_HoaDon.GetBySoHoaDon(soHoaDon);
                if (rs2.next()) {
                    dup = true;
                    rowCount++;
                    soHoaDon = dateFormat.format(d);
                } else {
                    dup = false;
                }
            } while (dup);

        } catch (SQLException ex) {
            System.out.println("Lỗi số hóa đơn");
        }

        return soHoaDon;
    }

    public void XuatHoaDon(int idhd) {
        try {
            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src/GUI/rptXuatHD.jrxml");

            map.put("MaHD", idhd);
//            System.out.println(map.put("MaHD", idhd));
            JasperPrint p = JasperFillManager.fillReport(report, map, DBconnection.conn);
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "test.pdf");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        LamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void themKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themKHActionPerformed
        jdlThemNhanhKH jdl = new jdlThemNhanhKH(run.jdl, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_themKHActionPerformed

    private void txtTongCongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTongCongKeyReleased
        String chuoi = txtTongCong.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtTongCong.setText(sotien);
    }//GEN-LAST:event_txtTongCongKeyReleased

    private void txtGiamGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyReleased
        String chuoi = txtGiamGia.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtGiamGia.setText(sotien);
        double tongTien = 0;
        for (int i = 0; i < tbl_CThoadon.getRowCount(); i++) {
            tongTien += (BLL_ChuyenDoi.ChuyenSangSo(tbl_CThoadon.getValueAt(i, 5).toString()));           
        }
        tongTien = tongTien - so;
        txtTongCong.setText(BLL_ChuyenDoi.DinhDangSo(tongTien));
    }//GEN-LAST:event_txtGiamGiaKeyReleased
   
    private void LoaDataCBBLoaiSP() {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbLoaiSP.getModel();
        ResultSet rs = DAO.DAO_HoaDon.GetAllLoaiSP();
        try {
            while (rs.next()) {
                Object tenLoai = rs.getString("TenLoaiSP");
                Object maLoai = rs.getString("MaLoaiSP");
                My_CBB mb = new My_CBB(maLoai, tenLoai);
                cbbModel.addElement(mb);
            }
        } catch (SQLException ex) {
            ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnChon;
    private javax.swing.JToggleButton btnLamMoi;
    private javax.swing.JToggleButton btnThanhToan;
    public static javax.swing.JComboBox<String> cbbKhachHang;
    private javax.swing.JComboBox<String> cbbLoaiSP;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblDienthoai;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblGiaSP;
    private javax.swing.JLabel lblGiamgia;
    private javax.swing.JLabel lblKhachhang;
    private javax.swing.JLabel lblKhachtra;
    private javax.swing.JLabel lblNgaytao;
    private javax.swing.JLabel lblNhanvien;
    private javax.swing.JLabel lblSoHD;
    private javax.swing.JLabel lblTensp;
    private javax.swing.JLabel lblTiendu;
    private javax.swing.JLabel lblTimkh;
    private javax.swing.JLabel lblTongcong;
    private javax.swing.JLabel lblgiaSP;
    private javax.swing.JPanel pnlBang;
    private javax.swing.JPanel pnlDanhsachsp;
    private javax.swing.JPanel pnlKhung;
    private javax.swing.JPanel pnlLoaisp;
    private javax.swing.JPanel pnlThanhtoan;
    private javax.swing.JPanel pnlThongtin;
    private javax.swing.JPanel pnlthongtintk;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JScrollPane tblSanpham;
    public static javax.swing.JTable tbl_CThoadon;
    public static javax.swing.JTable tbl_SP;
    private javax.swing.JButton themKH;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGiaSP;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtKhachTra;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearchKH;
    private javax.swing.JTextField txtSearchSP;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTienDu;
    private javax.swing.JTextField txtTongCong;
    // End of variables declaration//GEN-END:variables
}
