/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DTO.DTO_LoaiSanPham;
import DTO.DTO_SanPham;
import DTO.DTO_User;
import static GUI.Pnl_Khachhang.Tbl_Khachhang;
import static GUI.Pnl_Khachhang.imageName;
import static GUI.Pnl_Qlnhanvien.imageName;

import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Minh
 */
public class Pnl_Sanpham extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Sanpham() {
        initComponents();
        BLL.BLL_SanPham.DoDuLieu(tblSanpham);
        LoaDataCBBLoaiSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhungchinh = new javax.swing.JPanel();
        pnlTacvu = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        lblTimkiem = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        pnlThongtinSP = new javax.swing.JPanel();
        lblMasp = new javax.swing.JLabel();
        lblTensp = new javax.swing.JLabel();
        lblLoaisp = new javax.swing.JLabel();
        lblGianhap = new javax.swing.JLabel();
        lblTonkho = new javax.swing.JLabel();
        lblGiaban = new javax.swing.JLabel();
        pnlImg = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        txtTensp = new javax.swing.JTextField();
        txtGianhap = new javax.swing.JTextField();
        spnTonkho = new javax.swing.JSpinner();
        cbbLoaisp = new javax.swing.JComboBox<>();
        lblGhichu = new javax.swing.JLabel();
        txtGiaban = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhichu = new javax.swing.JTextArea();
        pnlTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanpham = new javax.swing.JTable();

        pnlKhungchinh.setBackground(new java.awt.Color(204, 204, 255));

        pnlTacvu.setBackground(new java.awt.Color(204, 204, 255));
        pnlTacvu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ "));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Edit.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLammoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnLammoi.setText(" MỚI");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        lblTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimkiem.setText("TÌM KIẾM");

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTacvuLayout = new javax.swing.GroupLayout(pnlTacvu);
        pnlTacvu.setLayout(pnlTacvuLayout);
        pnlTacvuLayout.setHorizontalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlTacvuLayout.setVerticalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLammoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlThongtinSP.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));

        lblMasp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblMasp.setText("Mã sản phẩm ");

        lblTensp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTensp.setText("Tên sản phẩm");

        lblLoaisp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblLoaisp.setText("Loại sản phẩm");

        lblGianhap.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGianhap.setText("Giá nhập");

        lblTonkho.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTonkho.setText("Tồn kho ");

        lblGiaban.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGiaban.setText("Giá bán");

        pnlImg.setBackground(new java.awt.Color(255, 255, 255));
        pnlImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlImgMouseClicked(evt);
            }
        });

        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlImgLayout = new javax.swing.GroupLayout(pnlImg);
        pnlImg.setLayout(pnlImgLayout);
        pnlImgLayout.setHorizontalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        pnlImgLayout.setVerticalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        txtGianhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGianhapKeyReleased(evt);
            }
        });

        spnTonkho.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cbbLoaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaispActionPerformed(evt);
            }
        });

        lblGhichu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGhichu.setText("Ghi chú");

        txtGiaban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiabanKeyReleased(evt);
            }
        });

        txtGhichu.setColumns(20);
        txtGhichu.setRows(5);
        jScrollPane5.setViewportView(txtGhichu);

        javax.swing.GroupLayout pnlThongtinSPLayout = new javax.swing.GroupLayout(pnlThongtinSP);
        pnlThongtinSP.setLayout(pnlThongtinSPLayout);
        pnlThongtinSPLayout.setHorizontalGroup(
            pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnlImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGianhap)
                    .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTensp)
                        .addComponent(lblMasp))
                    .addComponent(lblGhichu))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTonkho)
                            .addComponent(lblGiaban)
                            .addComponent(lblLoaisp))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnTonkho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        pnlThongtinSPLayout.setVerticalGroup(
            pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMasp)
                            .addComponent(lblTonkho)
                            .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnTonkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTensp)
                            .addComponent(lblLoaisp)
                            .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGianhap)
                            .addComponent(lblGiaban)
                            .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                                .addComponent(lblGhichu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                    .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                        .addComponent(pnlImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlKhungchinhLayout = new javax.swing.GroupLayout(pnlKhungchinh);
        pnlKhungchinh.setLayout(pnlKhungchinhLayout);
        pnlKhungchinhLayout.setHorizontalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlThongtinSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTacvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlKhungchinhLayout.setVerticalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTacvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThongtinSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlTable.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        tblSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MaSP", "TenSP", "MaloaiSP", "GiaNhap", "GiaBan", "TonKho", "Hình"
            }
        ));
        tblSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanphamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanpham);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhungchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhungchinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public static String imageNameSP;
    File f;
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        txtGhichu.setText("");
        txtGiaban.setText("");
        txtGianhap.setText("");
        txtMasp.setText("");
        txtTensp.setText("");

    }//GEN-LAST:event_btnLammoiActionPerformed

    private void cbbLoaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaispActionPerformed
    private void LoaDataCBBLoaiSP() {
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbLoaisp.getModel();
        ResultSet rs = DAO.DAO_loaiSanPham.GetALL();
        try {
            while (rs.next()) {
                Object tenLoai = rs.getString("TenLoaiSP");
                Object maLoai = rs.getString("MaLoaiSP");
                My_CBB mb = new My_CBB(maLoai, tenLoai);
                cbbModel.addElement(mb);
            }
        } catch (SQLException ex) {
            ThongBao.ThongBao("Lỗi lấy dữ liệu", "Thông báo");
        }
    }

    public static boolean saveImage(File file) {
        File dir = new File("IMG");
        if (!dir.exists()) {
            dir.mkdirs();
        }

        try {
            File newFile = new File(dir, file.getName());
            Path source = Paths.get(file.getAbsolutePath());
            Path destination = Paths.get(newFile.getAbsolutePath());
            Files.copy(source, destination, StandardCopyOption.REPLACE_EXISTING);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    private void tblSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanphamMouseClicked
        int vitri = tblSanpham.getSelectedRow();
        DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cbbLoaisp.getModel();
        for (int i = 0; i < cbbLoaisp.getItemCount(); i++) {
            My_CBB mb = (My_CBB) cbbModel.getElementAt(i);
            String loaisp = mb.value.toString();
            if (loaisp.equals((tblSanpham.getValueAt(vitri, 3)))) {
                cbbLoaisp.setSelectedIndex(i);
            }
        }
        txtMasp.setText(tblSanpham.getValueAt(vitri, 1).toString());
        txtTensp.setText(tblSanpham.getValueAt(vitri, 2).toString());
        txtGianhap.setText(tblSanpham.getValueAt(vitri, 4).toString());
        spnTonkho.setValue(Integer.parseInt(tblSanpham.getValueAt(vitri, 6).toString()));
        txtGiaban.setText(tblSanpham.getValueAt(vitri, 5).toString());
        ResultSet rs = DAO.DAO_SanPham.GetMoTa(tblSanpham.getValueAt(vitri, 1).toString());
        try {
            while (rs.next()) {
                txtGhichu.setText(rs.getString("Mota"));
            }
        } catch (SQLException ex) {

        }
//        ImageIcon ii = new ImageIcon(new ImageIcon(tbl_sanpham.getValueAt(vitri, 7).toString()).getImage().getScaledInstance(Lbl_Image.getWidth(), Lbl_Image.getHeight(), Image.SCALE_SMOOTH));
//        Lbl_Image.setIcon(ii);
//        imageNameSP = tbl_sanpham.getValueAt(vitri, 7).toString();
        lbl_ImageSP(tblSanpham.getValueAt(vitri, 7).toString());
    }//GEN-LAST:event_tblSanphamMouseClicked
    public void lbl_ImageSP(String ImagePath) {
        ImageIcon icon = new ImageIcon("IMG\\" + ImagePath);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), image.SCALE_SMOOTH));
        lblImage.setIcon(icon1);
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        DTO.DTO_SanPham sanPham = new DTO_SanPham();
        sanPham.setMaSP(txtMasp.getText());
        sanPham.setTenSP(txtTensp.getText());
        sanPham.setGiaBan(BLL_ChuyenDoi.ChuyenSangSo(txtGiaban.getText()));
        sanPham.setGiaNhap(BLL_ChuyenDoi.ChuyenSangSo(txtGianhap.getText()));
        My_CBB mb = (My_CBB) cbbLoaisp.getSelectedItem();
        sanPham.setLoaiSP((mb.value.toString()));
        sanPham.setTonKho(String.valueOf(spnTonkho.getValue()));
        sanPham.setGhiChu(txtGhichu.getText());
        sanPham.setHinh(imageNameSP);
        boolean kq = BLL.BLL_SanPham.KiemTra(sanPham);
        if (kq) {
                ThongBao.ThongBao("Thêm thành công", "Thông báo");
                saveImage(f);
                DAO.DAO_SanPham.ThemSP(sanPham);
                BLL.BLL_SanPham.DoDuLieu(tblSanpham);
            }

       
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int sodongduocchon = tblSanpham.getSelectedRowCount();
        if (sodongduocchon != 1) {
            ThongBao.ThongBao("Bạn cần chọn 1 dòng để sửa", "Thông báo");
            return;
        }
        DTO.DTO_SanPham sanPham = new DTO_SanPham();
        sanPham.setGiaBan(BLL_ChuyenDoi.ChuyenSangSo(txtGiaban.getText()));
        sanPham.setGiaNhap(BLL_ChuyenDoi.ChuyenSangSo(txtGianhap.getText()));
        sanPham.setMaSP(txtMasp.getText());
        sanPham.setTenSP(txtTensp.getText());
        My_CBB mb = (My_CBB) cbbLoaisp.getSelectedItem();
        sanPham.setLoaiSP((mb.value.toString()));
        sanPham.setTonKho(String.valueOf(spnTonkho.getValue()));
        sanPham.setGhiChu(txtGhichu.getText());
        sanPham.setHinh(imageNameSP);
        sanPham.setDonvitinh("cái");
        boolean kq = BLL.BLL_SanPham.KiemTra(sanPham);
        if (kq) {
            ThongBao.ThongBao("Sửa thành công", "Thông báo");
            saveImage(f);
            DAO.DAO_SanPham.suaSP(sanPham);
            BLL.BLL_SanPham.DoDuLieu(tblSanpham);

        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tblSanpham.getSelectedRowCount() != 1) {
            ThongBao.ThongBao("Bạn chưa chọn sản phẩm để xóa", "Thông báo");
            return;
        } else {
            int kq = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có chắc chắn muốn xóa không",
                    "Thông báo", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                int cacdong[] = tblSanpham.getSelectedRows();
                for (int i = 0; i < cacdong.length; i++) {
                    String sanpham = tblSanpham.getValueAt(cacdong[i], 1).toString();
                    int kq1 = DAO.DAO_SanPham.XoaSP(sanpham);
                    if (kq1 < 1) {
                        ThongBao.ThongBao("Sản phẩm này đang có dữ liệu", "Thông báo");
                        return;
                    }
                }
            }
            BLL.BLL_SanPham.DoDuLieu(tblSanpham);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        String tukhoa = txtTimkiem.getText();
        BLL.BLL_SanPham.DoDuLieu(tblSanpham, tukhoa);
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void pnlImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlImgMouseClicked

    }//GEN-LAST:event_pnlImgMouseClicked

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int resuft = file.showOpenDialog(null);
        if (resuft == JFileChooser.APPROVE_OPTION) {
            f = file.getSelectedFile();
            imageNameSP = f.getAbsolutePath();
            ImageIcon ii = new ImageIcon(new ImageIcon(imageNameSP).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
            lblImage.setIcon(ii);
            try {
                imageNameSP = f.getName();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblImageMouseClicked

    private void txtGianhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGianhapKeyReleased
        String chuoi = txtGianhap.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtGianhap.setText(sotien);
    }//GEN-LAST:event_txtGianhapKeyReleased

    private void txtGiabanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiabanKeyReleased
        String chuoi = txtGiaban.getText();
        double so = BLL.BLL_ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.BLL_ChuyenDoi.DinhDangSo(so);
        txtGiaban.setText(sotien);
    }//GEN-LAST:event_txtGiabanKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbLoaisp;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblGiaban;
    private javax.swing.JLabel lblGianhap;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLoaisp;
    private javax.swing.JLabel lblMasp;
    private javax.swing.JLabel lblTensp;
    private javax.swing.JLabel lblTimkiem;
    private javax.swing.JLabel lblTonkho;
    private javax.swing.JPanel pnlImg;
    private javax.swing.JPanel pnlKhungchinh;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTacvu;
    private javax.swing.JPanel pnlThongtinSP;
    private javax.swing.JSpinner spnTonkho;
    public static javax.swing.JTable tblSanpham;
    private javax.swing.JTextArea txtGhichu;
    private javax.swing.JTextField txtGiaban;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtTensp;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
