/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DTO.DTO_Khachhang;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Minh
 */
public class Pnl_Khachhang extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Khachhang() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pnlKhungchinh = new javax.swing.JPanel();
        pnlTacvu = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        lblTimkiem = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        pnlThongtinkh = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        lblSdt = new javax.swing.JLabel();
        lblGioitinh = new javax.swing.JLabel();
        lblDiachi = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        lblGhichu = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Txt_Ghichu = new javax.swing.JTextArea();
        cbbGioitinh = new javax.swing.JComboBox<>();
        txtDiachi = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        pnlAnh = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblNgaysinh = new javax.swing.JLabel();
        txtNgaysinh = new com.toedter.calendar.JDateChooser();
        lblLoaiKH = new javax.swing.JLabel();
        Cbb_LoaiKH = new javax.swing.JComboBox<>();
        pnlTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl_Khachhang = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlKhungchinh.setBackground(new java.awt.Color(255, 255, 255));

        pnlTacvu.setBackground(new java.awt.Color(204, 204, 255));
        pnlTacvu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ "));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Edit.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLammoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnLammoi.setText(" MỚI");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        lblTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimkiem.setText("TÌM KIẾM");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTacvuLayout = new javax.swing.GroupLayout(pnlTacvu);
        pnlTacvu.setLayout(pnlTacvuLayout);
        pnlTacvuLayout.setHorizontalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlTacvuLayout.setVerticalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLammoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlThongtinkh.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinkh.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        lblMaKH.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblMaKH.setText("Mã khách hàng");

        lblTenKH.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTenKH.setText("Tên khách hàng");

        lblSdt.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblSdt.setText("Số điện thoại");

        lblGioitinh.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGioitinh.setText("Giới tính");

        lblDiachi.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblDiachi.setText("Địa chỉ");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblEmail.setText("Email");

        lblGhichu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGhichu.setText("Ghi chú");

        Txt_Ghichu.setColumns(20);
        Txt_Ghichu.setRows(5);
        jScrollPane5.setViewportView(Txt_Ghichu);

        cbbGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));
        cbbGioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioitinhActionPerformed(evt);
            }
        });

        pnlAnh.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAnhLayout = new javax.swing.GroupLayout(pnlAnh);
        pnlAnh.setLayout(pnlAnhLayout);
        pnlAnhLayout.setHorizontalGroup(
            pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        pnlAnhLayout.setVerticalGroup(
            pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnhLayout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblNgaysinh.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblNgaysinh.setText("Ngày sinh");

        txtNgaysinh.setDateFormatString("dd-MM-yyyy");

        lblLoaiKH.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblLoaiKH.setText("Loại khách hàng");

        Cbb_LoaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Silver", "Gold", "Platinum" }));

        javax.swing.GroupLayout pnlThongtinkhLayout = new javax.swing.GroupLayout(pnlThongtinkh);
        pnlThongtinkh.setLayout(pnlThongtinkhLayout);
        pnlThongtinkhLayout.setHorizontalGroup(
            pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinkhLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGioitinh)
                    .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTenKH)
                        .addComponent(lblMaKH))
                    .addComponent(lblGhichu)
                    .addComponent(lblNgaysinh))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongtinkhLayout.createSequentialGroup()
                        .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(cbbGioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongtinkhLayout.createSequentialGroup()
                                .addComponent(lblLoaiKH)
                                .addGap(18, 18, 18)
                                .addComponent(Cbb_LoaiKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlThongtinkhLayout.createSequentialGroup()
                                .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiachi)
                                    .addComponent(lblEmail)
                                    .addComponent(lblSdt))
                                .addGap(36, 36, 36)
                                .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(13, 13, 13))
        );
        pnlThongtinkhLayout.setVerticalGroup(
            pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinkhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongtinkhLayout.createSequentialGroup()
                        .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaKH)
                            .addComponent(lblDiachi)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKH)
                            .addComponent(lblSdt)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioitinh)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgaysinh)
                            .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLoaiKH)
                                .addComponent(Cbb_LoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(pnlThongtinkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhichu)))
                    .addGroup(pnlThongtinkhLayout.createSequentialGroup()
                        .addComponent(pnlAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        Tbl_Khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã khách hàng", "Tên khách hàng", "Giới tính", "Địa chỉ", "Phone ", "Email", "Ngày Sinh", "Loại khách hàng", "Hình"
            }
        ));
        Tbl_Khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_KhachhangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tbl_Khachhang);
        if (Tbl_Khachhang.getColumnModel().getColumnCount() > 0) {
            Tbl_Khachhang.getColumnModel().getColumn(0).setMinWidth(50);
            Tbl_Khachhang.getColumnModel().getColumn(0).setPreferredWidth(50);
            Tbl_Khachhang.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3)
                .addGap(0, 0, 0))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlKhungchinhLayout = new javax.swing.GroupLayout(pnlKhungchinh);
        pnlKhungchinh.setLayout(pnlKhungchinhLayout);
        pnlKhungchinhLayout.setHorizontalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                .addComponent(pnlThongtinkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlTacvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlKhungchinhLayout.setVerticalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTacvu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(pnlThongtinkh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhungchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhungchinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
   public static String imageName;
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        LamMoi();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        DTO.DTO_Khachhang KH = new DTO_Khachhang();
        KH.setMaKH(txtMaKH.getText());
        KH.setTenKH(txtTenKH.getText());
        if (cbbGioitinh.getSelectedItem().equals("Nam")) {
            KH.setGioitinh(true);
        } else {
            KH.setGioitinh(false);
        }
        KH.setDiachi(txtDiachi.getText());
        KH.setSdt(txtSdt.getText());
        KH.setEmail(txtEmail.getText());
        KH.setMota(Txt_Ghichu.getText());
        KH.setLoaiKh(Cbb_LoaiKH.getSelectedItem().toString());
        if (txtNgaysinh.getDate() == null) {
        } else {
            KH.setNgaysinh(BLL_ChuyenDoi.GetDate(txtNgaysinh.getDate()));
        }
        KH.setHinh(imageName);
        boolean kq = BLL.BLL_Khachhang.KiemTraThem(KH);
        if (kq) {
            ThongBao.ThongBao("Thêm thành công", "Thông báo");
            DAO.DAO_Khachhang.ThemKH(KH);
            BLL.BLL_Khachhang.DoDuLieu(Tbl_Khachhang);
        }


    }//GEN-LAST:event_btnThemActionPerformed
    File f;
    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int resuft = file.showOpenDialog(null);
        if (resuft == JFileChooser.APPROVE_OPTION) {
            f = file.getSelectedFile();
            imageName = f.getAbsolutePath();
            ImageIcon ii = new ImageIcon(new ImageIcon(imageName).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
            lblImage.setIcon(ii);
            try {
                imageName = f.getName();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblImageMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DTO.DTO_Khachhang KH = new DTO_Khachhang();
        int sodongduocchon = Tbl_Khachhang.getSelectedRowCount();
        if (sodongduocchon != 1) {
            ThongBao.ThongBao("Bạn cần chọn 1 dòng để sửa", "Thông báo");
            return;
        }
        KH.setMaKH(txtMaKH.getText());
        KH.setTenKH(txtTenKH.getText());
        if (cbbGioitinh.getSelectedItem().equals("Nam")) {
            KH.setGioitinh(true);
        } else {
            KH.setGioitinh(false);
        }
        KH.setDiachi(txtDiachi.getText());
        KH.setNgaysinh(BLL_ChuyenDoi.GetDate(txtNgaysinh.getDate()));
        KH.setSdt(txtSdt.getText());
        KH.setEmail(txtEmail.getText());
        KH.setMota(Txt_Ghichu.getText());
        KH.setLoaiKh(Cbb_LoaiKH.getSelectedItem().toString());
        KH.setHinh(imageName);
        boolean kq = BLL.BLL_Khachhang.KiemTraSua(KH);
        if (kq) {
            ThongBao.ThongBao("Sửa thành công", "Thông báo");
            DAO.DAO_Khachhang.SuaKH(KH);
            BLL.BLL_Khachhang.DoDuLieu(Tbl_Khachhang);
        }


    }//GEN-LAST:event_btnSuaActionPerformed
    public static boolean saveImage(File file) {
        File dir = new File("IMG");
        if (!dir.exists()) {
            dir.mkdirs();
        }

        try {
            File newFile = new File(dir, file.getName());
            Path source = Paths.get(file.getAbsolutePath());
            Path destination = Paths.get(newFile.getAbsolutePath());
            Files.copy(source, destination, StandardCopyOption.REPLACE_EXISTING);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public void lbl_ImageKH(String ImagePath) {
        ImageIcon icon = new ImageIcon("IMG\\" + ImagePath);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), image.SCALE_SMOOTH));
        lblImage.setIcon(icon1);
    }
    private void Tbl_KhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_KhachhangMouseClicked
        // SimpleDateFormat d=new SimpleDateFormat("dd-MM-yyyy");
        int vitri = Tbl_Khachhang.getSelectedRow();
        txtMaKH.setText(Tbl_Khachhang.getValueAt(vitri, 1).toString());
        txtTenKH.setText(Tbl_Khachhang.getValueAt(vitri, 2).toString());
        cbbGioitinh.setSelectedItem(Tbl_Khachhang.getValueAt(vitri, 3).toString());
        txtDiachi.setText(Tbl_Khachhang.getValueAt(vitri, 4).toString());
        txtSdt.setText(Tbl_Khachhang.getValueAt(vitri, 5).toString());
        txtEmail.setText(Tbl_Khachhang.getValueAt(vitri, 6).toString());
        txtNgaysinh.setDate(BLL.BLL_ChuyenDoi.getDate(Tbl_Khachhang.getValueAt(vitri, 7).toString()));
        Cbb_LoaiKH.setSelectedItem(Tbl_Khachhang.getValueAt(vitri, 8).toString());
        ImageIcon ii = new ImageIcon(new ImageIcon(Tbl_Khachhang.getValueAt(vitri, 9).toString()).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
        lblImage.setIcon(ii);
        lbl_ImageKH(Tbl_Khachhang.getValueAt(vitri, 9).toString());
        ResultSet rs = DAO.DAO_Khachhang.GetMoTa(Tbl_Khachhang.getValueAt(vitri, 1).toString());
        try {
            while (rs.next()) {
                Txt_Ghichu.setText(rs.getString("Mota"));
            }
        } catch (SQLException ex) {

        }
        txtMaKH.setFocusable(false);
    }//GEN-LAST:event_Tbl_KhachhangMouseClicked
    private void LamMoi() {
        txtDiachi.setText("");
        txtEmail.setText("");
        Txt_Ghichu.setText("");
        txtMaKH.setText("");
        txtSdt.setText("");
        txtTenKH.setText("");
        txtMaKH.setFocusable(true);
        lblImage.setIcon(null);
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (Tbl_Khachhang.getSelectedRowCount() != 1) {
            ThongBao.ThongBao("Bạn chưa chọn khách hàng để xóa", "Thông báo");
            return;
        } else {
            int kq = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có chắc chắn muốn xóa không",
                    "Thông báo", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                int cacdong[] = Tbl_Khachhang.getSelectedRows();
                for (int i = 0; i < cacdong.length; i++) {
                    String MaKH = Tbl_Khachhang.getValueAt(cacdong[i], 1).toString();
                    DAO.DAO_Khachhang.XoaKH(MaKH);
                }
            }
            BLL.BLL_Khachhang.DoDuLieu(Tbl_Khachhang);
            LamMoi();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        BLL.BLL_Khachhang.DoDuLieu(Tbl_Khachhang, txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void cbbGioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbGioitinhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbb_LoaiKH;
    public static javax.swing.JTable Tbl_Khachhang;
    private javax.swing.JTextArea Txt_Ghichu;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbGioitinh;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblGioitinh;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLoaiKH;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblNgaysinh;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTimkiem;
    private javax.swing.JPanel pnlAnh;
    private javax.swing.JPanel pnlKhungchinh;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTacvu;
    private javax.swing.JPanel pnlThongtinkh;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaKH;
    private com.toedter.calendar.JDateChooser txtNgaysinh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
