/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_LoaiSanPham;
import DTO.DTO_NhanVien;
import static GUI.Pnl_Hoadon.tbl_SP;
import static GUI.Pnl_Qlnhanvien.imageName;
import static GUI.Pnl_Qlnhanvien.tblNhanVien;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static GUI.Pnl_Sanpham.tblSanpham;

/**
 *
 * @author Minh
 */
public class Pnl_Loaisanpham extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Loaisanpham() {
        initComponents();
        BLL.BLL_loaiSanPham.DoDuLieu(tbl_Loaisanpham);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhung = new javax.swing.JPanel();
        pnlTacvu = new javax.swing.JPanel();
        ptnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        lblTimkiem = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        pnlThongtinSP = new javax.swing.JPanel();
        lblMasp = new javax.swing.JLabel();
        lblTensp = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        txtTensp = new javax.swing.JTextField();
        lblGhichu = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhichu = new javax.swing.JTextArea();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Loaisanpham = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        pnlKhung.setBackground(new java.awt.Color(255, 255, 255));

        pnlTacvu.setBackground(new java.awt.Color(204, 204, 255));
        pnlTacvu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ "));

        ptnThem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ptnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add.png"))); // NOI18N
        ptnThem.setText(" THÊM");
        ptnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Edit.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnMoi.setText(" MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        lblTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimkiem.setText("TÌM KIẾM");

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });
        txtTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimkiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTacvuLayout = new javax.swing.GroupLayout(pnlTacvu);
        pnlTacvu.setLayout(pnlTacvuLayout);
        pnlTacvuLayout.setHorizontalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ptnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTacvuLayout.setVerticalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ptnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlThongtinSP.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));

        lblMasp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblMasp.setText("Mã sản phẩm ");

        lblTensp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTensp.setText("Tên sản phẩm");

        lblGhichu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGhichu.setText("Ghi chú");

        txtGhichu.setColumns(20);
        txtGhichu.setRows(5);
        jScrollPane5.setViewportView(txtGhichu);

        javax.swing.GroupLayout pnlThongtinSPLayout = new javax.swing.GroupLayout(pnlThongtinSP);
        pnlThongtinSP.setLayout(pnlThongtinSPLayout);
        pnlThongtinSPLayout.setHorizontalGroup(
            pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                        .addComponent(lblMasp)
                        .addGap(18, 18, 18)
                        .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTensp)
                            .addComponent(lblGhichu))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTensp)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlThongtinSPLayout.setVerticalGroup(
            pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMasp)
                    .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTensp)
                    .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGhichu)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTable.setBackground(new java.awt.Color(204, 204, 255));
        pnlTable.setBorder(javax.swing.BorderFactory.createTitledBorder("  "));

        tbl_Loaisanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã loại sản phẩm", "Tên loại sản phẩm", "Ghi chú"
            }
        ));
        tbl_Loaisanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LoaisanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Loaisanpham);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlKhungLayout = new javax.swing.GroupLayout(pnlKhung);
        pnlKhung.setLayout(pnlKhungLayout);
        pnlKhungLayout.setHorizontalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhungLayout.createSequentialGroup()
                .addComponent(pnlThongtinSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTacvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKhungLayout.setVerticalGroup(
            pnlKhungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTacvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlThongtinSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        LamMoi();

    }//GEN-LAST:event_btnMoiActionPerformed

    private void LamMoi() {
        txtMasp.setText("");
        txtTensp.setText("");
        txtGhichu.setText("");
    }
    private void ptnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnThemActionPerformed
        DTO.DTO_LoaiSanPham loaisanPham = new DTO_LoaiSanPham();
        loaisanPham.setMaSP(txtMasp.getText().toString());
        loaisanPham.setTenSP(txtTensp.getText());
        loaisanPham.setGhichu(txtGhichu.getText());
        boolean kq = BLL.BLL_loaiSanPham.KiemTra(loaisanPham);
        if (kq) {
            int so = DAO.DAO_loaiSanPham.ThemSP(loaisanPham);
            if (so > 0) {
                ThongBao.ThongBao("Thêm thành công", "Thông báo");
                BLL.BLL_loaiSanPham.DoDuLieu(tbl_Loaisanpham);
            }

        }
    }//GEN-LAST:event_ptnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DTO.DTO_LoaiSanPham sanPham = new DTO_LoaiSanPham();
        sanPham.setMaSP(txtMasp.getText());
        sanPham.setTenSP(txtTensp.getText());
        sanPham.setGhichu(txtGhichu.getText());
        boolean kq = BLL.BLL_loaiSanPham.KiemTra(sanPham);
        if (kq) {
            int so = DAO.DAO_loaiSanPham.SuaSP(sanPham);
            if (so > 0) {
                ThongBao.ThongBao("Sửa thành công", "Thông báo");
                BLL.BLL_loaiSanPham.DoDuLieu(tbl_Loaisanpham);
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tbl_Loaisanpham.getSelectedRowCount() != 1) {
            ThongBao.ThongBao("Bạn chưa chọn loại sản phẩm để xóa", "Thông báo");
            return;
        } else {
            int kq = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có chắc chắn muốn xóa không",
                    "Thông báo", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                int cacdong[] = tbl_Loaisanpham.getSelectedRows();
                for (int i = 0; i < cacdong.length; i++) {
                    String MaNV = tbl_Loaisanpham.getValueAt(cacdong[i], 1).toString();
                    int kq1 = DAO.DAO_loaiSanPham.XoaSP(MaNV);
                    if (kq1 < 1) {
                        ThongBao.ThongBao("Loại sản phẩm này đang có dữ liệu", "Thông báo");
                        return;
                    }
                }
            }
            BLL.BLL_loaiSanPham.DoDuLieu(tbl_Loaisanpham);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void txtTimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimkiemKeyReleased
        String tukhoa = txtTimkiem.getText();
        BLL.BLL_loaiSanPham.DoDuLieu(tbl_Loaisanpham, tukhoa);
    }//GEN-LAST:event_txtTimkiemKeyReleased

    private void tbl_LoaisanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LoaisanphamMouseClicked
        int vitri = tbl_Loaisanpham.getSelectedRow();
        txtMasp.setText(tbl_Loaisanpham.getValueAt(vitri, 1).toString());
        txtTensp.setText(tbl_Loaisanpham.getValueAt(vitri, 2).toString());
        ResultSet rs = DAO.DAO_loaiSanPham.GetMoTa(tbl_Loaisanpham.getValueAt(vitri, 1).toString());
        try {
            while (rs.next()) {
                txtGhichu.setText(rs.getString("MoTa"));
            }
        } catch (SQLException ex) {

        }

        txtMasp.setFocusable(false);

    }//GEN-LAST:event_tbl_LoaisanphamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblMasp;
    private javax.swing.JLabel lblTensp;
    private javax.swing.JLabel lblTimkiem;
    private javax.swing.JPanel pnlKhung;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTacvu;
    private javax.swing.JPanel pnlThongtinSP;
    private javax.swing.JButton ptnThem;
    private javax.swing.JTable tbl_Loaisanpham;
    private javax.swing.JTextArea txtGhichu;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtTensp;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
