/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DTO.DTO_NhanVien;
import static GUI.Pnl_Luong.tbl_luong;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.Patch;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Minh
 */
public class Pnl_Qlnhanvien extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Qlnhanvien() {
        initComponents();
        imageName = "";
        BLL.BLL_NhanVien.DoDuLieu(Pnl_Qlnhanvien.tblNhanVien);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhungchinh = new javax.swing.JPanel();
        pnlTacvu = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        lblTimkiem = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        pnlThongtinNV = new javax.swing.JPanel();
        lblManv = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        lblNgaysinh = new javax.swing.JLabel();
        lblGioitinh = new javax.swing.JLabel();
        lblChucvu = new javax.swing.JLabel();
        lblCmnd = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        cbbChucVu = new javax.swing.JComboBox<>();
        lblGhichu = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        lblDiachi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblSdt = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNgaylam = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jdcngaysinh = new com.toedter.calendar.JDateChooser();
        jdcngayvaolam = new com.toedter.calendar.JDateChooser();
        pnlTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        pnlKhungchinh.setBackground(new java.awt.Color(255, 255, 255));

        pnlTacvu.setBackground(new java.awt.Color(204, 204, 255));
        pnlTacvu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ "));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Edit.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnMoi.setText(" MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        lblTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimkiem.setText("TÌM KIẾM");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTacvuLayout = new javax.swing.GroupLayout(pnlTacvu);
        pnlTacvu.setLayout(pnlTacvuLayout);
        pnlTacvuLayout.setHorizontalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTacvuLayout.setVerticalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTimkiem)
                .addGap(7, 7, 7)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlThongtinNV.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinNV.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        lblManv.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblManv.setText("Mã nhân viên");

        lblTenNV.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTenNV.setText("Tên nhân viên");

        lblNgaysinh.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblNgaysinh.setText("Ngày sinh");

        lblGioitinh.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGioitinh.setText("Giới tính");

        lblChucvu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblChucvu.setText("Chức vụ");

        lblCmnd.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblCmnd.setText("Cmnd");

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lí ", "Nhân viên" }));

        lblGhichu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGhichu.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane5.setViewportView(txtGhiChu);

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        lblDiachi.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblDiachi.setText("Địa chỉ");

        lblSdt.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblSdt.setText("Số điện thoại");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblEmail.setText("Email");

        lblNgaylam.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblNgaylam.setText("Ngày vào làm");

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage.setOpaque(true);
        lblImage.setPreferredSize(new java.awt.Dimension(175, 228));
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        jdcngaysinh.setDateFormatString("dd-MM-yyyy");

        jdcngayvaolam.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout pnlThongtinNVLayout = new javax.swing.GroupLayout(pnlThongtinNV);
        pnlThongtinNV.setLayout(pnlThongtinNVLayout);
        pnlThongtinNVLayout.setHorizontalGroup(
            pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGioitinh)
                            .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTenNV)
                                .addComponent(lblManv))
                            .addComponent(lblGhichu))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                                .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(cbbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtDiaChi))
                                .addGap(38, 38, 38)
                                .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNgaysinh)
                                            .addComponent(lblChucvu)
                                            .addComponent(lblCmnd)
                                            .addComponent(lblNgaylam))
                                        .addGap(25, 25, 25)
                                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEmail)
                                            .addComponent(txtCMND)
                                            .addComponent(cbbChucVu, 0, 150, Short.MAX_VALUE)
                                            .addComponent(jdcngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jdcngayvaolam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addComponent(jScrollPane5)))
                    .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiachi)
                            .addComponent(lblSdt))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlThongtinNVLayout.setVerticalGroup(
            pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlThongtinNVLayout.createSequentialGroup()
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManv)
                            .addComponent(lblChucvu)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTenNV)
                                .addComponent(lblNgaysinh)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdcngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioitinh)
                            .addComponent(lblCmnd)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiachi)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSdt)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNgaylam))
                            .addComponent(jdcngayvaolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(pnlThongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGhichu))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlKhungchinhLayout = new javax.swing.GroupLayout(pnlKhungchinh);
        pnlKhungchinh.setLayout(pnlKhungchinhLayout);
        pnlKhungchinhLayout.setHorizontalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhungchinhLayout.createSequentialGroup()
                .addComponent(pnlThongtinNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlTacvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlKhungchinhLayout.setVerticalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhungchinhLayout.createSequentialGroup()
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTacvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongtinNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Giới tính", "Địa chỉ", "Số điện thoại", "Chức vụ", "Ngày sinh ", "CMND", "Email", "Ngày vào làm", "Hình"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(0).setMinWidth(30);
            tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhungchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhungchinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public static String imageName;
    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        LamMoi();
    }//GEN-LAST:event_btnMoiActionPerformed
    File f;
    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int resuft = file.showOpenDialog(null);
        if (resuft == JFileChooser.APPROVE_OPTION) {
            f = file.getSelectedFile();
            imageName = f.getAbsolutePath();
            ImageIcon ii = new ImageIcon(new ImageIcon(imageName).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
            lblImage.setIcon(ii);
            try {
                imageName = f.getName();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblImageMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        DTO.DTO_NhanVien NV = new DTO_NhanVien();
        NV.setMaNV(txtMaNV.getText());
        NV.setTenNV(txtTenNV.getText());
        if (cbbGioiTinh.getSelectedItem().equals("Nam")) {
            NV.setGioiTinh(true);
        } else {
            NV.setGioiTinh(false);
        }
        NV.setDiaChi(txtDiaChi.getText());
        NV.setSDT(txtSDT.getText());
        NV.setMoTa(txtGhiChu.getText());
        NV.setChucVu(cbbChucVu.getSelectedItem().toString());

        if (jdcngaysinh.getDate() == null) {
        } else {
            NV.setNgaySinh(BLL_ChuyenDoi.GetDate(jdcngaysinh.getDate()));
        }
        
        if (jdcngayvaolam.getDate() == null) {
        } else {
            NV.setNgayVaoLam(BLL_ChuyenDoi.GetDate(jdcngayvaolam.getDate()));
        }
        NV.setCMND(txtCMND.getText());
        NV.setEmail(txtEmail.getText());

        NV.setHinh(imageName);

        boolean kq = BLL.BLL_NhanVien.KiemTra(NV);
        if (kq) {
            ThongBao.ThongBao("Thêm thành công", "Thông báo");
            DAO.DAO_NhanVien.ThemNV(NV);
            saveImage(f);
            BLL.BLL_NhanVien.DoDuLieu(tblNhanVien);
            Pnl_Luong.LoaDataCBBNhanVien();
            LamMoi();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int vitri = tblNhanVien.getSelectedRow();
        txtMaNV.setText(tblNhanVien.getValueAt(vitri, 1).toString());
        txtTenNV.setText(tblNhanVien.getValueAt(vitri, 2).toString());
        cbbGioiTinh.setSelectedItem(tblNhanVien.getValueAt(vitri, 3).toString());
        txtDiaChi.setText(tblNhanVien.getValueAt(vitri, 4).toString());
        txtSDT.setText(tblNhanVien.getValueAt(vitri, 5).toString());
        cbbChucVu.setSelectedItem(tblNhanVien.getValueAt(vitri, 6).toString());
        jdcngaysinh.setDate(BLL.BLL_ChuyenDoi.getDate(tblNhanVien.getValueAt(vitri, 7).toString()));
        txtCMND.setText(tblNhanVien.getValueAt(vitri, 8).toString());
        txtEmail.setText(tblNhanVien.getValueAt(vitri, 9).toString());
        jdcngayvaolam.setDate(BLL.BLL_ChuyenDoi.getDate(tblNhanVien.getValueAt(vitri, 10).toString()));
//        ImageIcon ii = new ImageIcon(new ImageIcon(tblNhanVien.getValueAt(vitri, 11).toString()).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
//        lblImage.setIcon(ii);
        lbl_ImageNV(tblNhanVien.getValueAt(vitri, 11).toString());
        ResultSet rs = DAO.DAO_NhanVien.GetMoTa(tblNhanVien.getValueAt(vitri, 1).toString());
        try {
            while (rs.next()) {
                txtGhiChu.setText(rs.getString("MoTa"));
            }
        } catch (SQLException ex) {

        }
        txtMaNV.setFocusable(false);
    }//GEN-LAST:event_tblNhanVienMouseClicked
    public static boolean saveImage(File file) {
        File dir = new File("IMG");
        if (!dir.exists()) {
            dir.mkdirs();
        }

        try {
            File newFile = new File(dir, file.getName());
            Path source = Paths.get(file.getAbsolutePath());
            Path destination = Paths.get(newFile.getAbsolutePath());
            Files.copy(source, destination, StandardCopyOption.REPLACE_EXISTING);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void LamMoi() {
        txtMaNV.setText("");
        txtTenNV.setText("");
        cbbGioiTinh.setSelectedIndex(0);
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtGhiChu.setText("");
        cbbChucVu.setSelectedIndex(0);

        txtCMND.setText("");
        txtEmail.setText("");

        txtMaNV.setFocusable(true);
        lblImage.setIcon(null);

    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tblNhanVien.getSelectedRowCount() != 1) {
            ThongBao.ThongBao("Bạn chưa chọn nhân viên để xóa", "Thông báo");
            return;
        } else {
            int kq = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có chắc chắn muốn xóa không",
                    "Thông báo", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                int cacdong[] = tblNhanVien.getSelectedRows();
                for (int i = 0; i < cacdong.length; i++) {
                    String MaNV = tblNhanVien.getValueAt(cacdong[i], 1).toString();
                    int so = DAO.DAO_NhanVien.XoaNV(MaNV);
                    if (so != 1) {
                        ThongBao.ThongBao("Nhân viên này đang có dữ liệu", "Thông báo");
                    }
                }
            }
            BLL.BLL_NhanVien.DoDuLieu(tblNhanVien);
            Pnl_Luong.LoaDataCBBNhanVien();
            LamMoi();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DTO.DTO_NhanVien NV = new DTO_NhanVien();
        int sodongduocchon = tblNhanVien.getSelectedRowCount();
        if (sodongduocchon != 1) {
            ThongBao.ThongBao("Bạn cần chọn 1 dòng để sửa", "Thông báo");
            return;
        }
        NV.setMaNV(txtMaNV.getText());
        NV.setTenNV(txtTenNV.getText());
        if (cbbGioiTinh.getSelectedItem().equals("Nam")) {
            NV.setGioiTinh(true);
        } else {
            NV.setGioiTinh(false);
        }
        NV.setDiaChi(txtDiaChi.getText());
        NV.setSDT(txtSDT.getText());
        NV.setCMND(txtCMND.getText());
        NV.setMoTa(txtGhiChu.getText());
        NV.setChucVu(cbbChucVu.getSelectedItem().toString());
       
        NV.setEmail(txtEmail.getText());
        
        if (jdcngaysinh.getDate() == null) {
        } else {
            NV.setNgaySinh(BLL_ChuyenDoi.GetDate(jdcngaysinh.getDate()));
        }
        if (jdcngayvaolam.getDate() == null) {
        } else {
            NV.setNgayVaoLam(BLL_ChuyenDoi.GetDate(jdcngayvaolam.getDate()));
        }
        NV.setHinh(imageName);

        boolean kq = BLL.BLL_NhanVien.KiemTraSua(NV);
        if (kq) {
            ThongBao.ThongBao("Sửa thành công", "Thông báo");
            saveImage(f);
            DAO.DAO_NhanVien.SuaNV(NV);
            BLL.BLL_NhanVien.DoDuLieu(tblNhanVien);
            Pnl_Luong.LoaDataCBBNhanVien();
        }
    }//GEN-LAST:event_btnSuaActionPerformed
    public void lbl_ImageNV(String ImagePath) {
        ImageIcon icon = new ImageIcon("IMG\\" + ImagePath);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), image.SCALE_SMOOTH));
        lblImage.setIcon(icon1);
    }
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        BLL.BLL_NhanVien.DoDuLieu(tblNhanVien, txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMoi;
    public javax.swing.JButton btnSua;
    public javax.swing.JButton btnThem;
    public javax.swing.JButton btnXoa;
    public javax.swing.JComboBox<String> cbbChucVu;
    public javax.swing.JComboBox<String> cbbGioiTinh;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane5;
    public com.toedter.calendar.JDateChooser jdcngaysinh;
    public com.toedter.calendar.JDateChooser jdcngayvaolam;
    public javax.swing.JLabel lblChucvu;
    public javax.swing.JLabel lblCmnd;
    public javax.swing.JLabel lblDiachi;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblGhichu;
    public javax.swing.JLabel lblGioitinh;
    public javax.swing.JLabel lblImage;
    public javax.swing.JLabel lblManv;
    public javax.swing.JLabel lblNgaylam;
    public javax.swing.JLabel lblNgaysinh;
    public javax.swing.JLabel lblSdt;
    public javax.swing.JLabel lblTenNV;
    public javax.swing.JLabel lblTimkiem;
    public javax.swing.JPanel pnlKhungchinh;
    public javax.swing.JPanel pnlTable;
    public javax.swing.JPanel pnlTacvu;
    public javax.swing.JPanel pnlThongtinNV;
    public static javax.swing.JTable tblNhanVien;
    public javax.swing.JTextField txtCMND;
    public javax.swing.JTextField txtDiaChi;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextArea txtGhiChu;
    public javax.swing.JTextField txtMaNV;
    public javax.swing.JTextField txtSDT;
    public javax.swing.JTextField txtSearch;
    public javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
