/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import DTO.DTO_Khachhang;
import DTO.DTO_NCC;
import static GUI.Pnl_Khachhang.Tbl_Khachhang;
import static GUI.Pnl_Khachhang.imageName;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Minh
 */
public class Pnl_Nhacungcap extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Sanpham1
     */
    public Pnl_Nhacungcap() {
        initComponents();
        BLL.BLL_NCC.DoDuLieu(tbl_NCC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhungchinh = new javax.swing.JPanel();
        pnlTacvu = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        lblTimkiem = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        pnlThongtinNCC = new javax.swing.JPanel();
        lblMaNCC = new javax.swing.JLabel();
        lblTenNCC = new javax.swing.JLabel();
        lblDiachi = new javax.swing.JLabel();
        lblSdt = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        lblGhichu = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Txt_Ghichu = new javax.swing.JTextArea();
        txtEmail = new javax.swing.JTextField();
        pblTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_NCC = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        pnlKhungchinh.setBackground(new java.awt.Color(204, 204, 255));

        pnlTacvu.setBackground(new java.awt.Color(204, 204, 255));
        pnlTacvu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ "));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Edit.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Refresh.png"))); // NOI18N
        btnMoi.setText(" MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        lblTimkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimkiem.setText("TÌM KIẾM");

        txtTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimkiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlTacvuLayout = new javax.swing.GroupLayout(pnlTacvu);
        pnlTacvu.setLayout(pnlTacvuLayout);
        pnlTacvuLayout.setHorizontalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTacvuLayout.setVerticalGroup(
            pnlTacvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTacvuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlThongtinNCC.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinNCC.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà cung cấp"));

        lblMaNCC.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblMaNCC.setText("Mã NCC");

        lblTenNCC.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblTenNCC.setText("Tên NCC");

        lblDiachi.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblDiachi.setText("Địa chỉ");

        lblSdt.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblSdt.setText("Số điện thoại");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblEmail.setText("Email");

        lblGhichu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lblGhichu.setText("Ghi chú");

        Txt_Ghichu.setColumns(20);
        Txt_Ghichu.setRows(5);
        jScrollPane5.setViewportView(Txt_Ghichu);

        javax.swing.GroupLayout pnlThongtinNCCLayout = new javax.swing.GroupLayout(pnlThongtinNCC);
        pnlThongtinNCC.setLayout(pnlThongtinNCCLayout);
        pnlThongtinNCCLayout.setHorizontalGroup(
            pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSdt)
                    .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTenNCC)
                        .addComponent(lblMaNCC))
                    .addComponent(lblGhichu)
                    .addComponent(lblEmail)
                    .addComponent(lblDiachi))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTenNCC)
                        .addComponent(txtMaNCC)
                        .addComponent(txtSdt)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlThongtinNCCLayout.setVerticalGroup(
            pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNCC)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNCC)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSdt)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiachi))
                .addGap(20, 20, 20)
                .addGroup(pnlThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGhichu))
                .addContainerGap())
        );

        pblTable.setBackground(new java.awt.Color(204, 204, 255));
        pblTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));

        tbl_NCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NCC", "Tên NCC", "Số điện thoại", "Email", "Địa chỉ"
            }
        ));
        tbl_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NCCMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_NCC);

        javax.swing.GroupLayout pblTableLayout = new javax.swing.GroupLayout(pblTable);
        pblTable.setLayout(pblTableLayout);
        pblTableLayout.setHorizontalGroup(
            pblTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblTableLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pblTableLayout.setVerticalGroup(
            pblTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKhungchinhLayout = new javax.swing.GroupLayout(pnlKhungchinh);
        pnlKhungchinh.setLayout(pnlKhungchinhLayout);
        pnlKhungchinhLayout.setHorizontalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhungchinhLayout.createSequentialGroup()
                .addComponent(pnlThongtinNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTacvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pblTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKhungchinhLayout.setVerticalGroup(
            pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungchinhLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pblTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhungchinhLayout.createSequentialGroup()
                .addGroup(pnlKhungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlThongtinNCC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTacvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhungchinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhungchinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        lammoi();
    }//GEN-LAST:event_btnMoiActionPerformed
    private void lammoi() {
        txtMaNCC.setText("");
        txtTenNCC.setText("");
        txtDiachi.setText("");
        txtEmail.setText("");
        txtSdt.setText("");
        Txt_Ghichu.setText("");
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        DTO.DTO_NCC NCC = new DTO_NCC();
        NCC.setMaNCC(txtMaNCC.getText());
        NCC.setTenNCC(txtTenNCC.getText());
        NCC.setSdt(txtSdt.getText());
        NCC.setEmail(txtEmail.getText());
        NCC.setDiachi(txtDiachi.getText());
        NCC.setGhichu(Txt_Ghichu.getText());

        boolean kq = BLL.BLL_NCC.KiemTraThem(NCC);
        if (kq) {
            ThongBao.ThongBao("Thêm thành công", "Thông báo");
            DAO.DAO_NCC.ThemNCC(NCC);
            BLL.BLL_NCC.DoDuLieu(tbl_NCC);
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void tbl_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NCCMouseClicked
        int vitri = tbl_NCC.getSelectedRow();
        txtMaNCC.setText(tbl_NCC.getValueAt(vitri, 1).toString());
        txtTenNCC.setText(tbl_NCC.getValueAt(vitri, 2).toString());
        txtSdt.setText(tbl_NCC.getValueAt(vitri, 3).toString());
        txtEmail.setText(tbl_NCC.getValueAt(vitri, 4).toString());
        txtDiachi.setText(tbl_NCC.getValueAt(vitri, 5).toString());
        ResultSet rs = DAO.DAO_NCC.GetMoTa(tbl_NCC.getValueAt(vitri, 1).toString());
        try {
            while (rs.next()) {
                Txt_Ghichu.setText(rs.getString("Mota"));
            }
        } catch (SQLException ex) {

        }
        txtMaNCC.setFocusable(false);
    }//GEN-LAST:event_tbl_NCCMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DTO.DTO_NCC NCC = new DTO_NCC();
        int sodongduocchon = tbl_NCC.getSelectedRowCount();
        if (sodongduocchon != 1) {
            ThongBao.ThongBao("Bạn cần chọn 1 dòng để sửa", "Thông báo");
            return;
        }
        NCC.setMaNCC(txtMaNCC.getText());
        NCC.setTenNCC(txtTenNCC.getText());
        NCC.setSdt(txtSdt.getText());
        NCC.setEmail(txtEmail.getText());
        NCC.setDiachi(txtDiachi.getText());
        NCC.setGhichu(Txt_Ghichu.getText());
        boolean kq = BLL.BLL_NCC.KiemTraSua(NCC);
        if (kq) {
            ThongBao.ThongBao("Sửa thành công", "Thông báo");
            DAO.DAO_NCC.SuaNCC(NCC);
            BLL.BLL_NCC.DoDuLieu(tbl_NCC);
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tbl_NCC.getSelectedRowCount() != 1) {
            ThongBao.ThongBao("Bạn chưa chọn nhà cung cấp để xóa", "Thông báo");
            return;
        } else {
            int kq = JOptionPane.showConfirmDialog(new JFrame(), "Bạn có chắc chắn muốn xóa không",
                    "Thông báo", JOptionPane.YES_NO_OPTION);
            if (kq == JOptionPane.YES_OPTION) {
                int cacdong[] = tbl_NCC.getSelectedRows();
                for (int i = 0; i < cacdong.length; i++) {
                    String MaNCC = tbl_NCC.getValueAt(cacdong[i], 1).toString();
                    DAO.DAO_NCC.XoaNCC(MaNCC);
                }
            }
            BLL.BLL_NCC.DoDuLieu(tbl_NCC);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimkiemKeyReleased
        BLL.BLL_NCC.DoDuLieu(tbl_NCC, txtTimkiem.getText());
    }//GEN-LAST:event_txtTimkiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Txt_Ghichu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhichu;
    private javax.swing.JLabel lblMaNCC;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JLabel lblTenNCC;
    private javax.swing.JLabel lblTimkiem;
    private javax.swing.JPanel pblTable;
    private javax.swing.JPanel pnlKhungchinh;
    private javax.swing.JPanel pnlTacvu;
    private javax.swing.JPanel pnlThongtinNCC;
    public static javax.swing.JTable tbl_NCC;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
