/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChuyenDoi;
import java.sql.ResultSet;

/**
 *
 * @author admin
 */
public class pnlThongKe extends javax.swing.JPanel {

    /**
     * Creates new form pnlThongKe
     */
    public pnlThongKe() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnThongKe = new javax.swing.JTabbedPane();
        pnlLoinhuan = new javax.swing.JPanel();
        pnlDoanhthu = new javax.swing.JPanel();
        pnlKhungtongtien = new javax.swing.JPanel();
        lblTongLoiNhuan = new javax.swing.JLabel();
        lblTongLuongNV = new javax.swing.JLabel();
        lblTongTienNhap = new javax.swing.JLabel();
        lblTongTienBan = new javax.swing.JLabel();
        lblTongtienban1 = new javax.swing.JLabel();
        lblTongtiennhap1 = new javax.swing.JLabel();
        lblTongluongnv = new javax.swing.JLabel();
        lblTongloinhuan = new javax.swing.JLabel();
        btnCTBanHang = new javax.swing.JButton();
        btnCTNhapHang = new javax.swing.JButton();
        btnCTLuongNV = new javax.swing.JButton();
        pnlChonngay = new javax.swing.JPanel();
        jdcNgayKT4 = new com.toedter.calendar.JDateChooser();
        lblDenngay = new javax.swing.JLabel();
        jdcNgayBD4 = new com.toedter.calendar.JDateChooser();
        lblTungay = new javax.swing.JLabel();
        btnTKLN = new javax.swing.JButton();
        pnlLuongNV = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        pnlchonngaynv = new javax.swing.JPanel();
        jdcNgayKT = new com.toedter.calendar.JDateChooser();
        lblDenngayNV = new javax.swing.JLabel();
        jdcNgayBD = new com.toedter.calendar.JDateChooser();
        lblTungayNV = new javax.swing.JLabel();
        btnTKLuong = new javax.swing.JButton();
        pnlTongcong = new javax.swing.JPanel();
        lblTongcong = new javax.swing.JLabel();
        lblTongLuong = new javax.swing.JLabel();
        pnlDoanhthusp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTKSP = new javax.swing.JTable();
        pnlChonngaysp = new javax.swing.JPanel();
        jdcNgayKT2 = new com.toedter.calendar.JDateChooser();
        lblDenngaySP = new javax.swing.JLabel();
        jdcNgayBD2 = new com.toedter.calendar.JDateChooser();
        lblTungaySp = new javax.swing.JLabel();
        btnTKSP = new javax.swing.JButton();
        pnlTongdoanhthu = new javax.swing.JPanel();
        lblTongdoanhthu = new javax.swing.JLabel();
        lblTongdoanhthu1 = new javax.swing.JLabel();
        pnlTiengiamgia = new javax.swing.JPanel();
        lblTiengiamgia1 = new javax.swing.JLabel();
        lblTongTienGiamGia = new javax.swing.JLabel();
        pnlThongkesp = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSPNhap = new javax.swing.JTable();
        pnlChonngaySPnhap = new javax.swing.JPanel();
        jdcNgayKT3 = new com.toedter.calendar.JDateChooser();
        lblDenngayspNhap = new javax.swing.JLabel();
        jdcNgayBD3 = new com.toedter.calendar.JDateChooser();
        lblTungayspNhap = new javax.swing.JLabel();
        btnTKSPNhap = new javax.swing.JButton();
        pnltongcongSPnhap = new javax.swing.JPanel();
        lblTongcongSpnhap = new javax.swing.JLabel();
        lblTongCongSpNhap1 = new javax.swing.JLabel();

        pnlLoinhuan.setBackground(new java.awt.Color(204, 204, 255));

        pnlDoanhthu.setBackground(new java.awt.Color(204, 204, 255));
        pnlDoanhthu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doanh thu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        pnlKhungtongtien.setBackground(new java.awt.Color(204, 204, 255));
        pnlKhungtongtien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTongLoiNhuan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongLoiNhuan.setForeground(new java.awt.Color(255, 0, 0));
        lblTongLoiNhuan.setText("   ");

        lblTongLuongNV.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTongLuongNV.setText("   ");

        lblTongTienNhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTongTienNhap.setText("   ");

        lblTongTienBan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTongTienBan.setText("   ");

        lblTongtienban1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTongtienban1.setText("Tổng tiền bán hàng                 :");

        lblTongtiennhap1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTongtiennhap1.setText("Tổng tiền nhập hàng               :");

        lblTongluongnv.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTongluongnv.setText("Tổng tiền lương nhân viên      :");

        lblTongloinhuan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongloinhuan.setForeground(new java.awt.Color(255, 0, 0));
        lblTongloinhuan.setText("Tổng lợi nhuận                     :");

        btnCTBanHang.setText("Xem chi tiết");
        btnCTBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTBanHangActionPerformed(evt);
            }
        });

        btnCTNhapHang.setText("Xem chi tiết");
        btnCTNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTNhapHangActionPerformed(evt);
            }
        });

        btnCTLuongNV.setText("Xem chi tiết");
        btnCTLuongNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTLuongNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKhungtongtienLayout = new javax.swing.GroupLayout(pnlKhungtongtien);
        pnlKhungtongtien.setLayout(pnlKhungtongtienLayout);
        pnlKhungtongtienLayout.setHorizontalGroup(
            pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungtongtienLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongtienban1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTongluongnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTongtiennhap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTongloinhuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKhungtongtienLayout.createSequentialGroup()
                        .addComponent(lblTongLoiNhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(174, Short.MAX_VALUE))
                    .addGroup(pnlKhungtongtienLayout.createSequentialGroup()
                        .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTongLuongNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(lblTongTienNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTongTienBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCTBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCTLuongNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCTNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68))))
        );
        pnlKhungtongtienLayout.setVerticalGroup(
            pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhungtongtienLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongtienban1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTongTienBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCTBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addGap(19, 19, 19)
                .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCTNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblTongtiennhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongluongnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTongLuongNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCTLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(pnlKhungtongtienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongLoiNhuan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblTongloinhuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout pnlDoanhthuLayout = new javax.swing.GroupLayout(pnlDoanhthu);
        pnlDoanhthu.setLayout(pnlDoanhthuLayout);
        pnlDoanhthuLayout.setHorizontalGroup(
            pnlDoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhthuLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(pnlKhungtongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDoanhthuLayout.setVerticalGroup(
            pnlDoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhthuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(pnlKhungtongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlChonngay.setBackground(new java.awt.Color(204, 204, 255));
        pnlChonngay.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn ngày"));

        jdcNgayKT4.setDateFormatString("dd-MM-yyyy");

        lblDenngay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDenngay.setText("Đến ngày:");

        jdcNgayBD4.setDateFormatString("dd-MM-yyyy");

        lblTungay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTungay.setText("Từ ngày:");

        btnTKLN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTKLN.setText("Xem thống kê");
        btnTKLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKLNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChonngayLayout = new javax.swing.GroupLayout(pnlChonngay);
        pnlChonngay.setLayout(pnlChonngayLayout);
        pnlChonngayLayout.setHorizontalGroup(
            pnlChonngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonngayLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblTungay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayBD4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblDenngay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayKT4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnTKLN)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        pnlChonngayLayout.setVerticalGroup(
            pnlChonngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonngayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChonngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChonngayLayout.createSequentialGroup()
                        .addComponent(jdcNgayBD4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlChonngayLayout.createSequentialGroup()
                        .addGroup(pnlChonngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChonngayLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlChonngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTungay)
                                    .addComponent(lblDenngay)))
                            .addGroup(pnlChonngayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnTKLN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addComponent(jdcNgayKT4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout pnlLoinhuanLayout = new javax.swing.GroupLayout(pnlLoinhuan);
        pnlLoinhuan.setLayout(pnlLoinhuanLayout);
        pnlLoinhuanLayout.setHorizontalGroup(
            pnlLoinhuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDoanhthu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlChonngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLoinhuanLayout.setVerticalGroup(
            pnlLoinhuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoinhuanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlChonngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlDoanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnThongKe.addTab("Lợi nhuận", pnlLoinhuan);

        pnlLuongNV.setBackground(new java.awt.Color(204, 204, 255));

        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã lương", "Mã nhân viên", "Tên nhân viên", "Lương/giờ", "Số giờ làm", "Ngày làm", "Lương làm thêm", "Tổng lương/Ngày", "Mô tả"
            }
        ));
        jScrollPane1.setViewportView(tblLuong);
        if (tblLuong.getColumnModel().getColumnCount() > 0) {
            tblLuong.getColumnModel().getColumn(0).setMinWidth(30);
            tblLuong.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        pnlchonngaynv.setBackground(new java.awt.Color(204, 204, 255));
        pnlchonngaynv.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn ngày"));

        jdcNgayKT.setDateFormatString("dd-MM-yyyy");

        lblDenngayNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDenngayNV.setText("Đến ngày:");

        jdcNgayBD.setDateFormatString("dd-MM-yyyy");

        lblTungayNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTungayNV.setText("Từ ngày:");

        btnTKLuong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTKLuong.setText("Xem thống kê");
        btnTKLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlchonngaynvLayout = new javax.swing.GroupLayout(pnlchonngaynv);
        pnlchonngaynv.setLayout(pnlchonngaynvLayout);
        pnlchonngaynvLayout.setHorizontalGroup(
            pnlchonngaynvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlchonngaynvLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblTungayNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblDenngayNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnTKLuong)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        pnlchonngaynvLayout.setVerticalGroup(
            pnlchonngaynvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlchonngaynvLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlchonngaynvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcNgayBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlchonngaynvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlchonngaynvLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblTungayNV))
                        .addGroup(pnlchonngaynvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlchonngaynvLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDenngayNV)
                                .addGap(5, 5, 5))
                            .addComponent(jdcNgayKT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTKLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pnlTongcong.setBackground(new java.awt.Color(204, 204, 255));
        pnlTongcong.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTongcong.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongcong.setForeground(new java.awt.Color(255, 0, 0));
        lblTongcong.setText("Tổng cộng:");

        lblTongLuong.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongLuong.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlTongcongLayout = new javax.swing.GroupLayout(pnlTongcong);
        pnlTongcong.setLayout(pnlTongcongLayout);
        pnlTongcongLayout.setHorizontalGroup(
            pnlTongcongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTongcongLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblTongcong)
                .addGap(18, 18, 18)
                .addComponent(lblTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlTongcongLayout.setVerticalGroup(
            pnlTongcongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongcongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTongcongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongcong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLuongNVLayout = new javax.swing.GroupLayout(pnlLuongNV);
        pnlLuongNV.setLayout(pnlLuongNVLayout);
        pnlLuongNVLayout.setHorizontalGroup(
            pnlLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pnlchonngaynv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLuongNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLuongNVLayout.setVerticalGroup(
            pnlLuongNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLuongNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlchonngaynv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlTongcong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        tpnThongKe.addTab("Lương nhân viên", pnlLuongNV);

        pnlDoanhthusp.setBackground(new java.awt.Color(204, 204, 255));

        tblTKSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã HD", "Mã SP", "Tên sản phẩm", "Số lượng bán", "Giá tiền sản phẩm"
            }
        ));
        jScrollPane2.setViewportView(tblTKSP);

        pnlChonngaysp.setBackground(new java.awt.Color(204, 204, 255));
        pnlChonngaysp.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn ngày"));

        jdcNgayKT2.setDateFormatString("dd-MM-yyyy");

        lblDenngaySP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDenngaySP.setText("Đến ngày:");

        jdcNgayBD2.setDateFormatString("dd-MM-yyyy");

        lblTungaySp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTungaySp.setText("Từ ngày:");

        btnTKSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTKSP.setText("Xem thống kê");
        btnTKSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChonngayspLayout = new javax.swing.GroupLayout(pnlChonngaysp);
        pnlChonngaysp.setLayout(pnlChonngayspLayout);
        pnlChonngayspLayout.setHorizontalGroup(
            pnlChonngayspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonngayspLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblTungaySp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayBD2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblDenngaySP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayKT2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnTKSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChonngayspLayout.setVerticalGroup(
            pnlChonngayspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonngayspLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlChonngayspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcNgayBD2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChonngayspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlChonngayspLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblTungaySp))
                        .addGroup(pnlChonngayspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlChonngayspLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDenngaySP)
                                .addGap(5, 5, 5))
                            .addComponent(jdcNgayKT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(btnTKSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pnlTongdoanhthu.setBackground(new java.awt.Color(204, 204, 255));
        pnlTongdoanhthu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTongdoanhthu.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongdoanhthu.setForeground(new java.awt.Color(255, 0, 0));
        lblTongdoanhthu.setText("Tổng doanh thu");

        lblTongdoanhthu1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongdoanhthu1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlTongdoanhthuLayout = new javax.swing.GroupLayout(pnlTongdoanhthu);
        pnlTongdoanhthu.setLayout(pnlTongdoanhthuLayout);
        pnlTongdoanhthuLayout.setHorizontalGroup(
            pnlTongdoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTongdoanhthuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTongdoanhthu)
                .addGap(18, 18, 18)
                .addComponent(lblTongdoanhthu1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlTongdoanhthuLayout.setVerticalGroup(
            pnlTongdoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongdoanhthuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTongdoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongdoanhthu1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongdoanhthu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTiengiamgia.setBackground(new java.awt.Color(204, 204, 255));
        pnlTiengiamgia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTiengiamgia1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTiengiamgia1.setForeground(new java.awt.Color(255, 0, 0));
        lblTiengiamgia1.setText("Tiền giảm giá");

        lblTongTienGiamGia.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongTienGiamGia.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlTiengiamgiaLayout = new javax.swing.GroupLayout(pnlTiengiamgia);
        pnlTiengiamgia.setLayout(pnlTiengiamgiaLayout);
        pnlTiengiamgiaLayout.setHorizontalGroup(
            pnlTiengiamgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTiengiamgiaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTiengiamgia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTongTienGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pnlTiengiamgiaLayout.setVerticalGroup(
            pnlTiengiamgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiengiamgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTiengiamgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongTienGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiengiamgia1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDoanhthuspLayout = new javax.swing.GroupLayout(pnlDoanhthusp);
        pnlDoanhthusp.setLayout(pnlDoanhthuspLayout);
        pnlDoanhthuspLayout.setHorizontalGroup(
            pnlDoanhthuspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(pnlChonngaysp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoanhthuspLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(pnlTiengiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTongdoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlDoanhthuspLayout.setVerticalGroup(
            pnlDoanhthuspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhthuspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlChonngaysp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDoanhthuspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTongdoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTiengiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        tpnThongKe.addTab("Doanh thu sản phẩm", pnlDoanhthusp);

        pnlThongkesp.setBackground(new java.awt.Color(204, 204, 255));

        tblSPNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã PN", "Mã SP", "Tên sản phẩm", "Số lượng nhập", "Thành tiền"
            }
        ));
        jScrollPane3.setViewportView(tblSPNhap);

        pnlChonngaySPnhap.setBackground(new java.awt.Color(204, 204, 255));
        pnlChonngaySPnhap.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn ngày"));

        jdcNgayKT3.setDateFormatString("dd-MM-yyyy");

        lblDenngayspNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDenngayspNhap.setText("Đến ngày:");

        jdcNgayBD3.setDateFormatString("dd-MM-yyyy");

        lblTungayspNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTungayspNhap.setText("Từ ngày:");

        btnTKSPNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTKSPNhap.setText("Xem thống kê");
        btnTKSPNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKSPNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChonngaySPnhapLayout = new javax.swing.GroupLayout(pnlChonngaySPnhap);
        pnlChonngaySPnhap.setLayout(pnlChonngaySPnhapLayout);
        pnlChonngaySPnhapLayout.setHorizontalGroup(
            pnlChonngaySPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonngaySPnhapLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblTungayspNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayBD3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblDenngayspNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayKT3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnTKSPNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChonngaySPnhapLayout.setVerticalGroup(
            pnlChonngaySPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonngaySPnhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlChonngaySPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcNgayBD3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChonngaySPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlChonngaySPnhapLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblTungayspNhap))
                        .addGroup(pnlChonngaySPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlChonngaySPnhapLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDenngayspNhap)
                                .addGap(5, 5, 5))
                            .addComponent(jdcNgayKT3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(btnTKSPNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pnltongcongSPnhap.setBackground(new java.awt.Color(204, 204, 255));
        pnltongcongSPnhap.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTongcongSpnhap.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongcongSpnhap.setForeground(new java.awt.Color(255, 0, 0));
        lblTongcongSpnhap.setText("Tổng cộng:");

        lblTongCongSpNhap1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTongCongSpNhap1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnltongcongSPnhapLayout = new javax.swing.GroupLayout(pnltongcongSPnhap);
        pnltongcongSPnhap.setLayout(pnltongcongSPnhapLayout);
        pnltongcongSPnhapLayout.setHorizontalGroup(
            pnltongcongSPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltongcongSPnhapLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblTongcongSpnhap)
                .addGap(18, 18, 18)
                .addComponent(lblTongCongSpNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnltongcongSPnhapLayout.setVerticalGroup(
            pnltongcongSPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltongcongSPnhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnltongcongSPnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongCongSpNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongcongSpnhap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlThongkespLayout = new javax.swing.GroupLayout(pnlThongkesp);
        pnlThongkesp.setLayout(pnlThongkespLayout);
        pnlThongkespLayout.setHorizontalGroup(
            pnlThongkespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(pnlChonngaySPnhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongkespLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnltongcongSPnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlThongkespLayout.setVerticalGroup(
            pnlThongkespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongkespLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlChonngaySPnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnltongcongSPnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tpnThongKe.addTab("Thống kê sản phẩm nhập", pnlThongkesp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpnThongKe)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTKSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKSPActionPerformed
        try {
            String NgayBD2 = BLL_ChuyenDoi.GetDate(jdcNgayBD2.getDate());
            String NgayKT2 = BLL_ChuyenDoi.GetDate(jdcNgayKT2.getDate());
            BLL.BLL_ThongKe.DoDuLieuTKSP(tblTKSP, NgayBD2, NgayKT2);
            
            ResultSet rs = DAO.DAO_ThongKe.getTongTienBan(NgayBD2, NgayKT2);
            ResultSet rs1 = DAO.DAO_ThongKe.getTongTienGiamGia(NgayBD2, NgayKT2);
            while(rs.next()){
                lblTongdoanhthu1.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("TongTienBan")));
            }
            while(rs1.next()){
                lblTongTienGiamGia.setText(BLL_ChuyenDoi.DinhDangSo(rs1.getDouble("TongTienGiamGia")));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTKSPActionPerformed

    private void btnTKSPNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKSPNhapActionPerformed
        try {
            String NgayBD3 = BLL_ChuyenDoi.GetDate(jdcNgayBD3.getDate());
            String NgayKT3 = BLL_ChuyenDoi.GetDate(jdcNgayKT3.getDate());
            BLL.BLL_ThongKe.DoDuLieuTKSPNhap(tblSPNhap, NgayBD3, NgayKT3);
            ResultSet rs = DAO.DAO_ThongKe.getTongTienNhap(NgayBD3, NgayKT3);
            while(rs.next()){
                lblTongCongSpNhap1.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("TongTienNhap")));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTKSPNhapActionPerformed

    private void btnTKLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKLuongActionPerformed
        try {
            String NgayBD = BLL_ChuyenDoi.GetDate(jdcNgayBD.getDate());
            String NgayKT = BLL_ChuyenDoi.GetDate(jdcNgayKT.getDate());
            BLL.BLL_ThongKe.DoDuLieuTKLuong(tblLuong, NgayBD, NgayKT);
            ResultSet rs = DAO.DAO_ThongKe.getTongLuong(NgayBD, NgayKT);
            while(rs.next()){
                lblTongLuong.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("TongLuong")));
            }
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnTKLuongActionPerformed

    private void btnTKLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKLNActionPerformed
        try {
            String NgayBD4 = BLL_ChuyenDoi.GetDate(jdcNgayBD4.getDate());
            String NgayKT4 = BLL_ChuyenDoi.GetDate(jdcNgayKT4.getDate());
            ResultSet rs1 = DAO.DAO_ThongKe.getTongTienBan(NgayBD4, NgayKT4);
            ResultSet rs2 = DAO.DAO_ThongKe.getTongTienNhap(NgayBD4, NgayKT4);
            ResultSet rs3 = DAO.DAO_ThongKe.getTongLuong(NgayBD4, NgayKT4);
            while (rs1.next()) {
                lblTongTienBan.setText(BLL_ChuyenDoi.DinhDangSo(rs1.getDouble("TongTienBan")));
            }
            while (rs2.next()) {
                lblTongTienNhap.setText(BLL_ChuyenDoi.DinhDangSo(rs2.getDouble("TongTienNhap")));
            }
            while (rs3.next()) {
                lblTongLuongNV.setText(BLL_ChuyenDoi.DinhDangSo(rs3.getDouble("TongLuong")));
            }
            double TongTienBan = BLL_ChuyenDoi.ChuyenSangSo(lblTongTienBan.getText());
            double TongTienNhap = BLL.BLL_ChuyenDoi.ChuyenSangSo(lblTongTienNhap.getText());
            double TongLuong = BLL_ChuyenDoi.ChuyenSangSo(lblTongLuongNV.getText());
            double LoiNhuan = TongTienBan - TongTienNhap - TongLuong;
            lblTongLoiNhuan.setText(BLL_ChuyenDoi.DinhDangSo(TongTienBan - TongTienNhap - TongLuong));
        } catch (Exception e) {
        }
        
        jdcNgayBD.setDate(jdcNgayBD4.getDate());
        jdcNgayBD2.setDate(jdcNgayBD4.getDate());
        jdcNgayBD3.setDate(jdcNgayBD4.getDate());
        jdcNgayKT.setDate(jdcNgayKT4.getDate());
        jdcNgayKT2.setDate(jdcNgayKT4.getDate());
        jdcNgayKT3.setDate(jdcNgayKT4.getDate());
        try {
            String NgayBD4 = BLL_ChuyenDoi.GetDate(jdcNgayBD4.getDate());
            String NgayKT4 = BLL_ChuyenDoi.GetDate(jdcNgayKT4.getDate());
            BLL.BLL_ThongKe.DoDuLieuTKSP(tblTKSP, NgayBD4, NgayKT4);
            ResultSet rs = DAO.DAO_ThongKe.getTongTienBan(NgayBD4, NgayKT4);
            ResultSet rs1 = DAO.DAO_ThongKe.getTongTienGiamGia(NgayBD4, NgayKT4);
            while(rs.next()){
                lblTongdoanhthu1.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("TongTienBan")));
            }
            while(rs1.next()){
                lblTongTienGiamGia.setText(BLL_ChuyenDoi.DinhDangSo(rs1.getDouble("TongTienGiamGia")));
            }
        } catch (Exception e) {
        }
        
        
        try {
            String NgayBD4 = BLL_ChuyenDoi.GetDate(jdcNgayBD4.getDate());
            String NgayKT4 = BLL_ChuyenDoi.GetDate(jdcNgayKT4.getDate());
            BLL.BLL_ThongKe.DoDuLieuTKSPNhap(tblSPNhap, NgayBD4, NgayKT4);
            ResultSet rs = DAO.DAO_ThongKe.getTongTienNhap(NgayBD4, NgayKT4);
            while(rs.next()){
                lblTongCongSpNhap1.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("TongTienNhap")));
            }
        } catch (Exception e) {
        }
        
        
        try {
            String NgayBD4 = BLL_ChuyenDoi.GetDate(jdcNgayBD4.getDate());
            String NgayKT4 = BLL_ChuyenDoi.GetDate(jdcNgayKT4.getDate());
            BLL.BLL_ThongKe.DoDuLieuTKLuong(tblLuong, NgayBD4, NgayKT4);
            ResultSet rs = DAO.DAO_ThongKe.getTongLuong(NgayBD4, NgayKT4);
            while(rs.next()){
                lblTongLuong.setText(BLL_ChuyenDoi.DinhDangSo(rs.getDouble("TongLuong")));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTKLNActionPerformed

    private void btnCTBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTBanHangActionPerformed
        tpnThongKe.setSelectedIndex(2);
        
    }//GEN-LAST:event_btnCTBanHangActionPerformed

    private void btnCTNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTNhapHangActionPerformed
        tpnThongKe.setSelectedIndex(3);
       
    }//GEN-LAST:event_btnCTNhapHangActionPerformed

    private void btnCTLuongNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTLuongNVActionPerformed
        tpnThongKe.setSelectedIndex(1);
       
    }//GEN-LAST:event_btnCTLuongNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTBanHang;
    private javax.swing.JButton btnCTLuongNV;
    private javax.swing.JButton btnCTNhapHang;
    private javax.swing.JButton btnTKLN;
    private javax.swing.JButton btnTKLuong;
    private javax.swing.JButton btnTKSP;
    private javax.swing.JButton btnTKSPNhap;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcNgayBD;
    private com.toedter.calendar.JDateChooser jdcNgayBD2;
    private com.toedter.calendar.JDateChooser jdcNgayBD3;
    private com.toedter.calendar.JDateChooser jdcNgayBD4;
    private com.toedter.calendar.JDateChooser jdcNgayKT;
    private com.toedter.calendar.JDateChooser jdcNgayKT2;
    private com.toedter.calendar.JDateChooser jdcNgayKT3;
    private com.toedter.calendar.JDateChooser jdcNgayKT4;
    private javax.swing.JLabel lblDenngay;
    private javax.swing.JLabel lblDenngayNV;
    private javax.swing.JLabel lblDenngaySP;
    private javax.swing.JLabel lblDenngayspNhap;
    private javax.swing.JLabel lblTiengiamgia1;
    private javax.swing.JLabel lblTongCongSpNhap1;
    private javax.swing.JLabel lblTongLoiNhuan;
    private javax.swing.JLabel lblTongLuong;
    private javax.swing.JLabel lblTongLuongNV;
    private javax.swing.JLabel lblTongTienBan;
    private javax.swing.JLabel lblTongTienGiamGia;
    private javax.swing.JLabel lblTongTienNhap;
    private javax.swing.JLabel lblTongcong;
    private javax.swing.JLabel lblTongcongSpnhap;
    private javax.swing.JLabel lblTongdoanhthu;
    private javax.swing.JLabel lblTongdoanhthu1;
    private javax.swing.JLabel lblTongloinhuan;
    private javax.swing.JLabel lblTongluongnv;
    private javax.swing.JLabel lblTongtienban1;
    private javax.swing.JLabel lblTongtiennhap1;
    private javax.swing.JLabel lblTungay;
    private javax.swing.JLabel lblTungayNV;
    private javax.swing.JLabel lblTungaySp;
    private javax.swing.JLabel lblTungayspNhap;
    private javax.swing.JPanel pnlChonngay;
    private javax.swing.JPanel pnlChonngaySPnhap;
    private javax.swing.JPanel pnlChonngaysp;
    private javax.swing.JPanel pnlDoanhthu;
    private javax.swing.JPanel pnlDoanhthusp;
    private javax.swing.JPanel pnlKhungtongtien;
    private javax.swing.JPanel pnlLoinhuan;
    private javax.swing.JPanel pnlLuongNV;
    private javax.swing.JPanel pnlThongkesp;
    private javax.swing.JPanel pnlTiengiamgia;
    private javax.swing.JPanel pnlTongcong;
    private javax.swing.JPanel pnlTongdoanhthu;
    private javax.swing.JPanel pnlchonngaynv;
    private javax.swing.JPanel pnltongcongSPnhap;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTable tblSPNhap;
    private javax.swing.JTable tblTKSP;
    private javax.swing.JTabbedPane tpnThongKe;
    // End of variables declaration//GEN-END:variables
}
